### ISSUE TITLE
enabled_plugins file permissions issue

### ISSUE THREAD

**Issue by mlcooper** [rabbitmq/chef-cookbook#174]
After installing RabbitMQ via the cookbook, the /etc/rabbitmq/enabled_plugins file is set to permissions of 640 and is owned by the root user and group.  Since Rabbit runs as the rabbitmq user, it can't read this file and I get this error: 

 Error description:
   {error,
       {cannot_read_enabled_plugins_file,"/etc/rabbitmq/enabled_plugins",
           eacces}}

This prevents RabbitMQ from staying up and running.  I have tried modifying the /etc/rabbitmq_enabled plugins file to chmod 644, however it always reverts back to 640.  I have seen numerous other articles online about this exact issue, but they all say to chmod 644 the file, but as I mentioned it always reverts to 640 when I do this.  

Has anyone else run into this issue with this cookbook?  If so, how do I fix this properly/permanently?  Thanks.

**Comment by piyushjalan02** [comment]
Switch to rabbitmq user and then enable plugin:

$su - rabbitmq
$rabbitmq-plugins enable rabbitmq_management
