### ISSUE TITLE
Chef >= 11.14.0 requirement

### ISSUE THREAD

**Issue by dpetzel** [rabbitmq/chef-cookbook#183]
The user provider leverages a relatively new attribute on an execute block (sensitive). This makes a ton of sense, but the challenge here is that was only introduced in 11.14.0 which has been out "all that long". At the very least I think the README needs to call out the Chef version as a requirement. It would be even more awesome, if a check was done for Chef version and only use sensitive on versions that support it.

**Comment by shrinathaithal** [comment]
Apologies for revoking a closed thread, but can you please give me some pointers on how should those stuck with Opsworks use this? As in, we are still stuck with Chef version 11.10, which we know is "old" now :(

**Comment by jjasghar** [comment]
Honestly, you'll have to fork an older version that worked with Opsworks and support it yourself.  The scope of this cookbook is the versions we say we support and running Chef not opsworks.

**Comment by nakedpony** [comment]
It's a pity that you ditched the Opsworks support just to use 'sensitive' in execute block.

**Comment by cmluciano** [comment]
Although the feature isn't backwards compatible, I believe the tradeoffs are important. Displaying plaintext passwords anywhere is a serious issue. 

I don't believe that this cookbook is incompatible with opsworks due to the sensitive parameter, rather just incompatible with chef < 11.14.
