### ISSUE TITLE
user with no password (used in rabbitmq_auth_mechanism_ssl plugin - EXTERNAL)

### ISSUE THREAD

**Issue by khuongdp** [rabbitmq/chef-cookbook#254]
Hi 

Is it possible to create a user without password? We use certificate (CN) to authorized the user

**Comment by michaelklishin** [comment]
Create a user with a blank password. 3.7.2 and later versions will refuse password logins with blank passwords but x509 certificate authentication with the `EXTERNAL` auth mechanism will still work, even if the password wasn't properly cleared with `rabbitmqctl clear_password`. Definitions import is another option.
