### ISSUE TITLE
rabbitmq-server with ssl-enabled management can't be started when selinux is enforcing on redhat 7

### ISSUE THREAD

**Issue by fonk** [rabbitmq/chef-cookbook#276]
Hi,

beam isn't allowed to bind to port 15671, which I think is suggested port on https://www.rabbitmq.com/management.html:

type=AVC msg=audit(1434564694.622:4462): avc:  denied  { name_bind } for  pid=22520 comm="beam" src=15671 scontext=system_u:system_r:rabbitmq_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket

**Comment by michaelklishin** [comment]
SELinux policies are out of scope for this cookbook.
