### ISSUE TITLE
'Example HA Policies' should be commented out in default attributes

### ISSUE THREAD

**Issue by cringdahl** [rabbitmq/chef-cookbook#287]
If `recipe[rabbitmq::policy_management]` is added to a run_list, the `'ha-all'` and `'ha-two'` example policies will be automatically added. Since this is likely not an intended default, they should be commented out, or moved to README.

Thanks!

**Comment by jjasghar** [comment]
Could you put together a PR for this? I like the idea of this being tunable.

**Comment by jklare** [comment]
This commit causes errors in version 4.9.0 and 4.10.0 since node['rabbitmq']['policies'] and node['rabbitmq']['disabled_policies'] is now undefined and in the recipe '.each' is called on them (leads to a nil:NilClass error). I will push a patch for this shortly.

**Comment by jklare** [comment]
Hi,

any chance we can backport that to the two tags that where affected (v4.9.0 and v4.10.0)? Or are you planning to release another version soon?

Cheers,
Jan

**Comment by jjasghar** [comment]
I'd like to release a new version, but there a ton of errors and dependancies issues in the travis runs. I need to clean those up before i can confidently do a release.

**Comment by johngun3** [comment]
There's no reason why you can't release a 4.9.1 and 4.10.1. I just wasted a bunch of time trying to figure out why chef was failing and it turns out it was because of https://github.com/rabbitmq/chef-cookbook/pull/399. It's shocking that the released version of the cookbook has a known simple bug and a new release with that bug fix hasn't been created.

**Comment by michaelklishin** [comment]
@jjasghar FWIW I think #399 is something that can be back ported to earlier series.

**Comment by jjasghar** [comment]
Understood. 

I've been attempting to fix the testing and Travis runs; but unfortunately I only have so many cycles. We have the fixed merge, and I was happy you found the fix. It will be released when the testing is resolved.

**Comment by michaelklishin** [comment]
This seems to be addressed in `attributes/default.rb`.
