### ISSUE TITLE
erlang cookie is not updating & clustering is not working

### ISSUE THREAD

**Issue by fnicholas** [rabbitmq/chef-cookbook#299]
So i wrote a wrapper cooking that depends on the rabbitmq v4.2.0. I noticed that the erlang cookie is not updating and the clustering is not working as well. 

Here's my cookbook with the Vagrant file. 

https://www.dropbox.com/s/v9tml535hzrfke1/lms-rabbitmq.zip?dl=0

Please can someone here help?

**Comment by jjasghar** [comment]
@sunggun-yu or @michaelklishin can you help @fnicholas out here?

**Comment by fnicholas** [comment]
@sunggun-yu or @michaelklishin please let me know if you need additional info. the README.md file is pretty detailed.

**Comment by michaelklishin** [comment]
Can you be more specific than "not working" and "not updating"? What exactly are the steps you take? Have you tried inspecting RabbitMQ log?

The cookbook looks OK and only defines a few resources.

**Comment by fnicholas** [comment]
In my earlier comment, I included my wrapper cookbook with all the attributes set to configure the cluster. 

RabbitMQ is working sort of. I can log on to the web GUI. The issue I am experiencing is the cluster setup aspect. I still can’t get the clustering to work as intended. The slave node is not joining the cluster.  The default[:lms][:rabbitmq][:erlang_cookie] attribute is not being set properly. In fact, it’s being ignored completely.

```ruby
default[:lms][:rabbitmq][:erlang_cookie] = 'IZYUKTS29483PNKRXCQAAIMNL4839'
```

The erlang cookie is not set to what I specified above. 
```ruby
[vagrant@rabbit1 ~]$ sudo cat /var/lib/rabbitmq/.erlang.cookie 
DVVXUWNLLYRZUYLYNJHC
```

As you can see, rabbit@rabbit2 is not part of the cluster. 

```bash
[vagrant@rabbit2 ~]$ sudo /etc/init.d/rabbitmq-server status
Status of node rabbit@rabbit2 ...
[{pid,15446},
---
```

```bash
[vagrant@rabbit1 ~]$ sudo rabbitmqctl cluster_status
Cluster status of node rabbit@rabbit1 ...
[{nodes,[{disc,[rabbit@rabbit1]}]},
 {running_nodes,[rabbit@rabbit1]},
 {cluster_name,<<"DLSG">>},
 {partitions,[]}]
```
I get the following error when I issue a cluster reset: 

```bash
[vagrant@rabbit1 ~]$ sudo /etc/init.d/rabbitmq-server stop
Stopping rabbitmq-server: rabbitmq-server.


[vagrant@rabbit1 ~]$ sudo rabbitmqctl reset
Resetting node rabbit@rabbit1 ...
Error: unable to connect to node rabbit@rabbit1: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@rabbit1]

rabbit@rabbit1:
  * connected to epmd (port 4369) on rabbit1
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on rabbit1
  * suggestion: start the node

current node details:
- node name: 'rabbitmq-cli-15418@rabbit1'
- home dir: /var/lib/rabbitmq
- cookie hash: xJ4bGCNGQ4+mF9J2KyCGLw==
```

```bash
[vagrant@rabbit1 ~]$ sudo /etc/init.d/rabbitmq-server start
Starting rabbitmq-server: SUCCESS
rabbitmq-server.
[vagrant@rabbit1 ~]$ sudo rabbitmqctl reset
Resetting node rabbit@rabbit1 ...
Error: mnesia_unexpectedly_running
```

**Comment by michaelklishin** [comment]
```
rabbit@rabbit1:
  * connected to epmd (port 4369) on rabbit1
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on rabbit1
  * suggestion: start the node
```

strongly suggests the node failed to start and inspecting the log may help you understand why.

As for `default[:lms][:rabbitmq][:erlang_cookie]`, this cookbook will manage the cookie and I'm not sure why it's necessary to make the wrapper do it.

**Comment by fnicholas** [comment]
please close this request. I got cluster working with my wrapper cookbook.

**Comment by jjasghar** [comment]
Can you tell us how you got it working with your wrapper cookbook? We'd like to be able to not need a wrapper and have this as a one stop shop.

Or if it's something our cookbook can't do would you mine writing up a section in the README.md so we can document steps so future people won't fall in this trap?

**Comment by jjasghar** [comment]
@fnicholas any luck on pulling this data together?

**Comment by jjasghar** [comment]
@fnicholas any chance you've had time to put how you fixed your problem together?
