### ISSUE TITLE
The following packages cannot be authenticated!   rabbitmq-server

### ISSUE THREAD

**Issue by kramvan1** [rabbitmq/chef-cookbook#300]
ubuntu 14.04   Did the apt-get update and upgrade, no difference.

vagrant@controller:~$ sudo apt-get -q -y install rabbitmq-server=3.4.3-2~cloud0
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  rabbitmq-server
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 0 B/4,040 kB of archives.
After this operation, 4,955 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  rabbitmq-server
E: There are problems and -y was used without --force-yes

Do we need the default recipe where the rabbitmq-server gets installed to add the following to cover these cases? 
   options '--force-yes'

my key list contains (apt-key list) the rabbitmq and cloud keys:
sudo apt-key list
## /etc/apt/trusted.gpg

pub   1024D/437D05B5 2004-09-12
uid                  Ubuntu Archive Automatic Signing Key ftpmaster@ubuntu.com
sub   2048g/79164387 2004-09-12

pub   1024D/FBB75451 2004-12-30
uid                  Ubuntu CD Image Automatic Signing Key cdimage@ubuntu.com

pub   4096R/C0B21F32 2012-05-11
uid                  Ubuntu Archive Automatic Signing Key (2012) ftpmaster@ubuntu.com

pub   4096R/EFE21092 2012-05-11
uid                  Ubuntu CD Image Automatic Signing Key (2012) cdimage@ubuntu.com

pub   4096R/EC4926EA 2012-08-14
uid                  Canonical Cloud Archive Signing Key ftpmaster@canonical.com
sub   4096R/ECD76E3E 2012-08-14

pub   1024D/056E8E56 2007-07-06
uid                  RabbitMQ Release Signing Key info@rabbitmq.com
sub   2048g/81181462 2007-07-06

Or is there a repo key missing somewhere in this path?

**Comment by ealwais** [comment]
create a file in `/etc/apt/apt.conf.d/90forceyes` with the following content:

```
APT::Get::Assume-Yes "true";
APT::Get::force-yes "true";
```

Then run the chef-client on the machine to resolve the issue.

**Comment by jjasghar** [comment]
We'll need to figure out a way to add this too. This would be a good time to update the version constraint on for the newer release. https://github.com/jjasghar/rabbitmq/issues/266

**Comment by kramvan1** [comment]
Looks like the apt cookbook at least has that dir created here: https://github.com/opscode-cookbooks/apt/blob/master/recipes/default.rb#L53
but I don't see a config in there for these Yes options, would look similar to: https://github.com/opscode-cookbooks/apt/blob/master/templates/default/10recommends.erb

Seems like a simple addition for the apt cookbook, then we could easily take advantage of that as a default attribute in the environment.

Something like:

templates/default/90forceyes.erb:

APT::Get::Assume-Yes "<%= node['apt']['confd']['assume_yes'] ? 1 : 0 %>";
APT::Get::force-yes "<%= node['apt']['confd']['force-yes'] ? 1 : 0 %>";


but I still really thing this is an issue with the repos themselves as force-yes is not a normal option to use.

**Comment by jjasghar** [comment]
So it shall be. Ill put it on my TODO to make the PR, unless someone beats me to it.

**Comment by jjasghar** [comment]
Hmm, yeah the more i chew on this the more i don't like the idea that we have to add something to the apt cookbook to get this to work. Maybe we should be tracking the Ubuntu packages. @michaelklishin are you watching the Ubuntu repos and may know what's going on here?

**Comment by jjasghar** [comment]
It looks like: https://review.openstack.org/#/c/211322/ is effected by this also.

**Comment by tas50** [comment]
I'm going to look into this today and see if we have any options other than adding a new attribute to the package provider in the client.

**Comment by tas50** [comment]
It looks like the correct apt config is APT::Get::AllowUnauthenticated "true";

We want to avoid assume yes and force yes since those will allow apt installs to continue when your apt sources are in a 1/2 complete state which can render the system unusable.  Ideally we'd allow untrusted package installs in the apt provider, but for now you might want to add the option to the cookbook to template a 99-enabled-unstrusted file in apt's .d dir.  It's a bit of a hack, but it will allow installing the package for now.

**Comment by jjasghar** [comment]
Yeah that's what it's starting to feel like. (the hack that is)

@michaelklishin any luck on figuring out what happened to your pkg becoming "untrusted?"

**Comment by michaelklishin** [comment]
@jjasghar we are not aware of any changes. Our package was last updated in July.

**Comment by jjasghar** [comment]
Hmm, i've seen this repo'd in a couple places now. This could be problematic.

**Comment by jjasghar** [comment]
https://github.com/jjasghar/rabbitmq/pull/301 Has been created, can i get some +1s and :rocket: s on it?

**Comment by michaelklishin** [comment]
#301 was merged.
