### ISSUE TITLE
Use a different mirror than rabbitmq.com?

### ISSUE THREAD

**Issue by martinb3** [rabbitmq/chef-cookbook#304]
Hello! We've noticed rabbitmq.com has been at least 3 times this year, which has shut down our CI pipeline. I [asked on their issue tracker](https://github.com/rabbitmq/rabbitmq-website/issues/77) about alternatives or ways I could help assist, but the response I received was that we should be using [packagecloud.io instead of rabbitmq.com](https://packagecloud.io/rabbitmq/rabbitmq-server) for downloading packages.

I would have just submitted this as a PR, but I figured I'd ask first -- is this something you have considered in the past? Are there dragons? I'd be glad to make the quick PR, if that's an acceptable path. I'd also be glad to make it some sort of begin/rescue if that's better.

Thanks in advance for your thoughts! :)

**Comment by jjasghar** [comment]
This is interesting. I havent really thought about it; and i guess if this is an issue we should have a way to variablize the way to get the pkg. I'd like other people from the community to weigh in here, to see if others are effected by this.

Any thoughts @michaelklishin ?

**Comment by martinb3** [comment]
Just posted this [in the original issue](https://github.com/rabbitmq/rabbitmq-website/issues/77#issuecomment-146853446), but it looks like PackageCloud and BinTray are no longer listed on the [Downloads page](http://www.rabbitmq.com/download.html) and haven't had releases of rabbitmq-server packages since August, and are out of sync with rabbitmq.com. Sounds like maybe Github is the only mirror right now with the latest versions.

**Comment by michaelklishin** [comment]
Package Cloud is [updated](https://packagecloud.io/rabbitmq/rabbitmq-server).

**Comment by michaelklishin** [comment]
This cookbook now uses Bintray or GitHub and allows for download source customization.
