### ISSUE TITLE
Is "notifies restart" necessary for enabling or disabling a policy?

### ISSUE THREAD

**Issue by mlcooper** [rabbitmq/chef-cookbook#319]
I am wondering if these two lines are necessary: 
`https://github.com/jjasghar/rabbitmq/blob/master/recipes/policy_management.rb#L31`
`https://github.com/jjasghar/rabbitmq/blob/master/recipes/policy_management.rb#L38`

I can't find any documentation that says that the RabbitMQ service needs to be restarted to set or delete policies.  

I can understand the need to do it for plugins and the management console, but the docs for creating a policy don't mention needing to restart the service.

Here's the article with `rabbitmqctl set_policy` documentation:
`https://www.rabbitmq.com/man/rabbitmqctl.1.man.html`

My concern is that in a running cluster, or if you have a single running RMQ server in production, the whole app needs to be restarted to work with policies which could cause some impact, but I'm not sure it's necessary to restart the app for policies.

**Comment by theundefined** [comment]
Why that's issue is closed?
I think restart is unnecessary. Are there any cases when restart always "must be"? If yes - maybe it's good idea to allow parametrize it and disable for environments where restart is not needed?

**Comment by michaelklishin** [comment]
I can't comment on why the issue was closed but policy changes do not require a node restart, that's for sure.

As for 3.4.0 it is also unnecessary to restart when enabling or disabling plugins (at least those that ship with RabbitMQ, custom plugins can do all sorts of things).

@jjasghar do you recall the context of this?

**Comment by jjasghar** [comment]
Honestly, nope. Normally I put a comment down or two, it seems I may have just gotten overly excited with `close issue`.

**Comment by michaelklishin** [comment]
Addressed in https://github.com/rabbitmq/chef-cookbook/commit/dafeae544e77939e5079931d0be8627b4f8f944e.
