### ISSUE TITLE
Add tcp linger option for tcp_listen_options  in rabbitmq.config

### ISSUE THREAD

**Issue by mgosalia** [rabbitmq/chef-cookbook#320]
Is there any way I could send out a pull request to get this merged sooner ?
Reference - https://www.rabbitmq.com/networking.html 
Search for "linger".

Needs to be added here - https://github.com/jjasghar/rabbitmq/blob/master/templates/default/rabbitmq.config.erb#L51

**Comment by mgosalia** [comment]
Here is the pull request - https://github.com/jjasghar/rabbitmq/pull/321

**Comment by michaelklishin** [comment]
#321 was merged.
