### ISSUE TITLE
Upgrade to RabbitMQ 3.6.0

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/chef-cookbook#329]
This is a heads-up and not an issue.

RabbitMQ 3.6.0 [is tagged](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_0). Note that in this release, server artifacts are distributed as `xz` archives and not `gz`. The cookbook will need adapting to this.

**Comment by markunsworth** [comment]
I was able to just change the version in the attributes file and it worked without any issues.

**Comment by majormoses** [comment]
I think this can be closed now: https://github.com/rabbitmq/chef-cookbook/blob/v5.3.1/attributes/default.rb#L3
