### ISSUE TITLE
Support disk_free_limit

### ISSUE THREAD

**Issue by jonapich** [rabbitmq/chef-cookbook#335]
Can we add the disk_free_limit stuff too?

RabbitMQ 3.6.0 and up can support this kind of syntax:

{disk_free_limit, "10GB"}

Below this version, we must supply an absolute nuumber without quotes:

{disk_free_limit, 10000000000}

**Comment by jjasghar** [comment]
We need to update the cookbook to `3.6.0` first ;)

https://github.com/jjasghar/rabbitmq/blob/master/attributes/default.rb#L2

**Comment by muikrad** [comment]
The absolute number works in 3.5, then the memory units were added to 3.6.0.

I am running 3.5.3 and it works wonder (using the bytes approach)

**Comment by michaelklishin** [comment]
Absolute values in bytes for free disk space limit has been around for ages.

**Comment by michaelklishin** [comment]
#350 was merged.
