### ISSUE TITLE
change_cluster_node_type broken since change

### ISSUE THREAD

**Issue by iramello** [rabbitmq/chef-cookbook#358]
Hi,
When using AWS Opsworks and Chef 11.10, due to this change:

https://github.com/jjasghar/rabbitmq/commit/01a4b9e730392cd041c06abe26c1b00461d8a24d#commitcomment-16952550

the change_cluster_node_type action does not work anymore.
Could you please revert?

**Comment by michaelklishin** [comment]
I'm afraid without extra information we cannot address this. Reverting without information isn't something I'd do either.
