### ISSUE TITLE
Install specific ERLANG version in debian distro

### ISSUE THREAD

**Issue by lvidela** [rabbitmq/chef-cookbook#383]
I am using the cookbook with berkshelf and it always install the 1:16.b.3 version of erlang, I'm looking a way to make it use OTP 18.2, is there any attribute I can use for this? I tried a few without luck.

thanks!

**Comment by devsibwarra** [comment]
@lisandro-truelogic Are you installing erlang from system packages, source, or the ESL package repos?  Check your erlang install method, then look at that repository to determine what installable versions are available

On Ubuntu 14.04, I use the ESL repos to install 18.3 with
```ruby
  'erlang' => {
    'install_method' => 'esl',
    'esl' => {
      'version' => '1:18.3'
    }
  }
```

**Comment by tas50** [comment]
@jjasghar This can get closed. As @devsibwarra mentioned this can be controlled in the erlang cookbook via attribute.

**Comment by michaelklishin** [comment]
There is now [a doc section](https://github.com/rabbitmq/chef-cookbook#provision-erlangotp-193-or-later) that explicitly explains how to provision a specific version via ESL repositories.
