### ISSUE TITLE
Enable SSL?

### ISSUE THREAD

**Issue by TemporarilyOffline** [rabbitmq/chef-cookbook#388]
I have followed the instructions in the README.md file for enabling SSL:
**
To enable SSL turn `ssl` to `true` and set the paths to your cacert, cert and key files.

``` ruby
node['rabbitmq']['ssl'] = true
node['rabbitmq']['ssl_cacert'] = '/path/to/cacert.pem'
node['rabbitmq']['ssl_cert'] = '/path/to/cert.pem'
node['rabbitmq']['ssl_key'] = '/path/to/key.pem'
```

A full list of SSL attributes can be found in [attributes/default.rb](attributes/default.rb).
**
I dug into the template code and noticed that it also wants version, dug into the code that calls the template and noticed that it wanted cipher, so I added those parameters:

``` ruby
default['rabbitmq']['ssl_versions'] = ['tlsv1.2']
default['rabbitmq']['ssl_ciphers'] = ['{ecdhe_ecdsa,aes_128_cbc,sha256}', '{ecdhe_ecdsa,aes_256_cbc,sha}']
```

I've converged with 4.8.0, 4.7.0 and 4.6.0

I'm running with test kitchen and chef 12.12.13

In all cases, there are no ssl options present in `/etc/rabbitmq/rabbitmq.conf` and nothing is listening on port 5671

Rabbitmq is installed and listening on 25762, 15672, 5672

Any suggestions for getting rabbitmq ssl working?

**Comment by michaelklishin** [comment]
TLS can be enabled only via [RabbitMQ configuration file](), which in all released versions is `rabbitmq.config`, not `rabbitmq-env.conf`.

It's not clear what exact you are doing. Modifying cookbook defaults, wrapping it in another cookbook, modifying node/environment/role attributes?

So the only suggestion I personally have: please specify *as specifically as possible* what has been tried so far.

**Comment by TemporarilyOffline** [comment]
I've wrapped the cookbook and set attributes in my attributes/default. In the style of `default['rabbitmq']['ssl'] = true`.  I am testing in test kitchen.

**Comment by TemporarilyOffline** [comment]
Checking in on this.  Any updates?

**Comment by jjasghar** [comment]
Sorry I haven't had a chance to look at this at all. I have multiple things on my plate, and when I have the cycles I'll be able to take a look. Hopefully I'll be able to circle back here. Maybe someone from the community can help in the time being.

**Comment by devsibwarra** [comment]
@TemporarilyOffline The `ssl_versions` and `ssl_ciphers` should only be necessary if you want to override the defaults for RabbitMQ.  Setting `node[rabbitmq][ssl] = true` should be all you need to get the proper sections added to `rabbitmq.config` if you're using the template provided by the rabbitmq cookbook.

Are you specifying a custom `node[rabbitmq][config_template_cookbook]`?  If yes, could the differences between your custom config template and the default cookbook template explain why ssl is not being configured?

**Comment by michaelklishin** [comment]
I don't see why `ssl_ciphers` and friends would not work in recent versions. Closing since well over a year has passed.
