### ISSUE TITLE
New version with MR 376

### ISSUE THREAD

**Issue by JorisAndrade** [rabbitmq/chef-cookbook#390]
Is it possible to make a new version containing https://github.com/rabbitmq/chef-cookbook/commit/46667ee24fa5b72d02061b257d187ade383f46e3 ? 

I can't use the lastest version of this cookbook because plugin management and virtualhost management is not working without it. 

Thanks in advance,

**Comment by jjasghar** [comment]
I'll set a release up today/tomorrow.

**Comment by jjasghar** [comment]
4.9.0 has been released.

**Comment by JorisAndrade** [comment]
Thanks !
