### ISSUE TITLE
Unable to enable plugins

### ISSUE THREAD

**Issue by pcon0718** [rabbitmq/chef-cookbook#392]
Hi Everyone, I am unable to enable plugins using a wrapper script with the rabbitmq cookbook.

I have put the following values in my wrapper script:

```
default['rabbitmq']['enabled_plugins'] = 'amqp_client', 'mochiweb', 'rabbitmq_management', 'rabbitmq_management_agent', 'rabbitmq_web_dispatch', 'webmachine'
default['rabbitmq']['disabled_plugins'] = []
default['rabbitmq']['community_plugins'] = {}
```
The cookbook converges fine. However no plugins ever get installed. 

[root@host1 rabbitmq]# rabbitmq-plugins list
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status:   * = running on rabbit@host1
 |/
[  ] amqp_client                       3.6.4
[  ] cowboy                            1.0.3
[  ] cowlib                            1.0.1
[  ] mochiweb                          2.13.1
[  ] rabbitmq_amqp1_0                  3.6.4
[  ] rabbitmq_auth_backend_ldap        3.6.4
[  ] rabbitmq_auth_mechanism_ssl       3.6.4
[  ] rabbitmq_consistent_hash_exchange 3.6.4
[  ] rabbitmq_event_exchange           3.6.4
[  ] rabbitmq_federation               3.6.4
[  ] rabbitmq_federation_management    3.6.4
[  ] rabbitmq_jms_topic_exchange       3.6.4
[  ] rabbitmq_management               3.6.4
[  ] rabbitmq_management_agent         3.6.4
[  ] rabbitmq_management_visualiser    3.6.4
[  ] rabbitmq_mqtt                     3.6.4
[  ] rabbitmq_recent_history_exchange  1.2.1
[  ] rabbitmq_sharding                 0.1.0
[  ] rabbitmq_shovel                   3.6.4
[  ] rabbitmq_shovel_management        3.6.4
[  ] rabbitmq_stomp                    3.6.4
[  ] rabbitmq_top                      3.6.4
[  ] rabbitmq_tracing                  3.6.4
[  ] rabbitmq_trust_store              3.6.4
[  ] rabbitmq_web_dispatch             3.6.4
[  ] rabbitmq_web_stomp                3.6.4
[  ] rabbitmq_web_stomp_examples       3.6.4
[  ] sockjs                            0.3.4
[  ] webmachine                        1.10.3

Not sure what I am doing wrong here. Any help would be appreciated. Thanks.

**Comment by devsibwarra** [comment]
@pcon0718 The `node['rabbitmq']['enabled_plugins']` setting must be an array.  In your wrapper script, it should look like one of these lines

```
default['rabbitmq']['enabled_plugins'] = ['amqp_client', 'mochiweb', 'rabbitmq_management', 'rabbitmq_management_agent', 'rabbitmq_web_dispatch', 'webmachine']

default['rabbitmq']['enabled_plugins'] = %w(amqp_client mochiweb rabbitmq_management rabbitmq_management_agent rabbitmq_web_dispatch webmachine)
```

**Comment by pcon0718** [comment]
Thanks @devsibwarra. I tried both, and the cookbook converges fine. However I am still not able to get the plugins to install.

**Comment by pcon0718** [comment]
Here is the code from my wrapper cookbook. 

./attributes/default.rb
```
# Define default attributes in this file.
default['rabbitmq']['version'] = '3.6.4'
default['rabbitmq']['rpm_package'] = "rabbitmq-server-#{node['rabbitmq']['version']}-1.noarch.rpm"
default['rabbitmq']['rpm_package_url'] = "http://rewrkatello1p.taketwo.online/pulp/repos/Default_Organization/Rockstar_EWR_Production/RockstarProdContentView/custom/Rockstar_Games_Custom/RSGCustom/#{node['rabbitmq']['version']}/"
default['rabbitmq']['mnesiadir'] = '/data1/rabbitmq/mnesia'
default['rabbitmq']['logdir'] = '/data1/rabbitmq/logs'
default['rabbitmq']['config_root'] = '/etc/rabbitmq'
default['rabbitmq']['config'] = "#{node['rabbitmq']['config_root']}/rabbitmq"
default['rabbitmq']['erlang_cookie_path'] = '/var/lib/rabbitmq/.erlang.cookie'
default['rabbitmq']['erlang_cookie'] = 'IYJOHBXYOCZQNYOEMZSI'
# plugins
default['rabbitmq']['enabled_plugins'] = %w(amqp_client mochiweb rabbitmq_management rabbitmq_management_agent rabbitmq_web_dispatch webmachine)
default['rabbitmq']['disabled_plugins'] = []
default['rabbitmq']['community_plugins'] = {}
```
./recipes/default.rb
```
# Default recipe that is executed at the start of this cookbook's processing.
include_recipe 'rabbitmq'
```

I can't get the erlang cookie file to change either, but figure I'd ask about that in another post.

**Comment by pcon0718** [comment]
Here is the code from my wrapper cookbook. 

./attributes/default.rb
```
# Define default attributes in this file.
default['rabbitmq']['version'] = '3.6.4'
default['rabbitmq']['rpm_package'] = "rabbitmq-server-#{node['rabbitmq']['version']}-1.noarch.rpm"
default['rabbitmq']['rpm_package_url'] = "http://katello.taketwo.online/pulp/repos/Default_Organization/CustomRepo/#{node['rabbitmq']['version']}/"
default['rabbitmq']['mnesiadir'] = '/data1/rabbitmq/mnesia'
default['rabbitmq']['logdir'] = '/data1/rabbitmq/logs'
default['rabbitmq']['config_root'] = '/etc/rabbitmq'
default['rabbitmq']['config'] = "#{node['rabbitmq']['config_root']}/rabbitmq"
default['rabbitmq']['erlang_cookie_path'] = '/var/lib/rabbitmq/.erlang.cookie'
default['rabbitmq']['erlang_cookie'] = 'IYJOHBXYOCZQNYOEMZSI'
# plugins
default['rabbitmq']['enabled_plugins'] = %w(amqp_client mochiweb rabbitmq_management rabbitmq_management_agent rabbitmq_web_dispatch webmachine)
default['rabbitmq']['disabled_plugins'] = []
default['rabbitmq']['community_plugins'] = {}
```
./recipes/default.rb
```
# Default recipe that is executed at the start of this cookbook's processing.
include_recipe 'rabbitmq'
```

I can't get the erlang cookie file to change either, but figure I'd ask about that in another post.

**Comment by pcon0718** [comment]
Here is the code from my wrapper cookbook. 

./attributes/default.rb
```
# Define default attributes in this file.
default['rabbitmq']['version'] = '3.6.4'
default['rabbitmq']['rpm_package'] = "rabbitmq-server-#{node['rabbitmq']['version']}-1.noarch.rpm"
default['rabbitmq']['rpm_package_url'] = "http://katello/pulp/repos/Default_Organization/CustomRepo/#{node['rabbitmq']['version']}/"
default['rabbitmq']['mnesiadir'] = '/data1/rabbitmq/mnesia'
default['rabbitmq']['logdir'] = '/data1/rabbitmq/logs'
default['rabbitmq']['config_root'] = '/etc/rabbitmq'
default['rabbitmq']['config'] = "#{node['rabbitmq']['config_root']}/rabbitmq"
default['rabbitmq']['erlang_cookie_path'] = '/var/lib/rabbitmq/.erlang.cookie'
default['rabbitmq']['erlang_cookie'] = 'IYJOHBXYOCZQNYOEMZSI'
# plugins
default['rabbitmq']['enabled_plugins'] = %w(amqp_client mochiweb rabbitmq_management rabbitmq_management_agent rabbitmq_web_dispatch webmachine)
default['rabbitmq']['disabled_plugins'] = []
default['rabbitmq']['community_plugins'] = {}
```
./recipes/default.rb
```
# Default recipe that is executed at the start of this cookbook's processing.
include_recipe 'rabbitmq'
```

I can't get the erlang cookie file to change either, but figure I'd ask about that in another post.

**Comment by devsibwarra** [comment]
The `rabbitmq` default recipe only installs RabbitMQ, sets up the configuration/erlang cookie, and manages the service.  You need to include the other desired recipes either in a role or your wrapper.

Here's a blurb from my wrapper cb; just include the recipes with settings you wish to manage/change
```
include_recipe 'rabbitmq'
include_recipe 'rabbitmq::mgmt_console'
include_recipe 'rabbitmq::plugin_management'
include_recipe 'rabbitmq::policy_management'
include_recipe 'rabbitmq::user_management'
include_recipe 'rabbitmq::virtualhost_management'
include_recipe 'rabbitmq::cluster'
```

The erlang cookie is only managed when clustering is enabled, which is disabled by default

**Comment by pcon0718** [comment]
That works. Thank you.
