### ISSUE TITLE
service rabbitmq-server on ubuntu 16.04

### ISSUE THREAD

**Issue by ohadedel** [rabbitmq/chef-cookbook#396]
When running the default recipe on ubuntu16.04
It does not create the rabbitmq.service file, so the systemd fails to start the service

Getting this message:
_Failed to restart rabbitmq-server.service: Unit rabbitmq-server.service not found._

**Comment by michaelklishin** [comment]
That's a bit too terse. What are the node attributes used?

systemd is suppoted by the Debian package as of https://github.com/rabbitmq/rabbitmq-server/issues/570, CentOS/Fedora/RHEL will follow in https://github.com/rabbitmq/rabbitmq-server/issues/932.

**Comment by michaelklishin** [comment]
This is the same as https://github.com/rabbitmq/chef-cookbook/issues/389, closing.
