### ISSUE TITLE
Erlang cookbook dependency is out of date

### ISSUE THREAD

**Issue by acholt** [rabbitmq/chef-cookbook#403]
Hi Guys

When using berks to install the rabbitmq cookbook it pulls the erlang cookbook version (1.3.2) and not latest which breaks. Should we not change the metadata to `depends 'erlang' ~> 4.0.0`?

Happy to do the PR if everyone is happy with that.

Cheers,
Andrew

**Comment by michaelklishin** [comment]
@acholt no objections from me. If you can include an Erlang cookbook change log with your PR, it would be easier to merge ;)

**Comment by acholt** [comment]
Thanks @michaelklishin. I was looking at the history of metadata file and see the version lock was removed for rabbitmq in commit [fixing for the tests](https://github.com/rabbitmq/chef-cookbook/commit/65ecf999c2b0b07919b708a6c3b18ae56a34430a) by @jjasghar.

Pinning makes sense as it ensures it works on that version, unless there are other issues that I'm missing?

What is the stance in the community before I change it?

**Comment by michaelklishin** [comment]
Different RabbitMQ versions support different Erlang version ranges. My guess is that was the idea. Current dependency gives the user a lot of flexibility when it comes to Erlang version used: just specify it in your Berksfile. So with that I consider this resolved (or well, no longer relevant).
