### ISSUE TITLE
Change default hearbeat to 60

### ISSUE THREAD

**Issue by tsupertramp** [rabbitmq/chef-cookbook#412]
Please change the heartbeat to 60 - This is new default and solves a lot of connection keep alive errors. Source: https://www.rabbitmq.com/heartbeats.html

https://github.com/rabbitmq/chef-cookbook/blob/master/attributes/default.rb#L150

Greetings, Thomas :)

**Comment by michaelklishin** [comment]
@tsupertramp feel free to submit a PR.

**Comment by tsupertramp** [comment]
https://github.com/rabbitmq/chef-cookbook/pull/413 :)
