### ISSUE TITLE
To install version 3.6.6

### ISSUE THREAD

**Issue by raju-divakaran** [rabbitmq/chef-cookbook#414]
Hello,

I am using this cookbook, and created like a wrapper cookbook. Which is pretty simple, where am just including the needed recipes from this cookbook.

My attribute file looks like
`default['rabbitmq']['version'] = '3.6.6'

default['rabbitmq']['clustering']['enable'] = true
default['rabbitmq']['erlang_cookie'] = 'AnyAlphaNumericStringWillDo'
default['rabbitmq']['clustering']['cluster_partition_handling'] = 'ignore'
default['rabbitmq']['clustering']['use_auto_clustering'] = false
default['rabbitmq']['clustering']['cluster_name'] = 'rbq_cluster'
default['rabbitmq']['clustering']['cluster_nodes'] = [
    {
        :name => 'rabbit@rabbit1',
        :type => 'disc'
    },
    {
        :name => 'rabbit@rabbit2',
        :type => 'disc'
    },
    {
        :name => 'rabbit@rabbit3',
        :type => 'disc'
    }
]

default['rabbitmq']['policies']['ha-two']['pattern'] = '*'
default['rabbitmq']['policies']['ha-two']['params'] = { 'ha-mode' => 'exactly', 'ha-params' => 2 }
default['rabbitmq']['policies']['ha-two']['priority'] = 1

default['rabbitmq']['default_user'] = 'admin'
default['rabbitmq']['default_pass'] = 'admin'

default['rabbitmq']['community_plugins'] = {

      'rabbitmq-delayed-message-exchange' => 'https://bintray.com/rabbitmq/community-plugins/download_file?file_path=rabbitmq_delayed_message_exchange-0.0.1.ez'
}`

and the recipe is

`
include_recipe 'rabbitmq::default'
include_recipe 'rabbitmq::cluster'
include_recipe 'rabbitmq::community_plugins'
`

Can anyone suggest a work around or faced the same issue !? May be I am missing something really small.

Thanks,

~Raju.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
I don't understand what the issue is. Please go into a bit more detail on the mailing list.

**Comment by raju-divakaran** [comment]
Thanks. To make it simple, I am trying to install rabbitmq version 3.6.6 and the cookbook keep installing 3.6.1.

**Comment by michaelklishin** [comment]
I don't think you want to modify default cookbook attributes. Environment, role or node attributes seem more appropriate to me? See https://docs.chef.io/attributes.html.
