### ISSUE TITLE
rabbitmq::policy_management tries to modify a frozen string

### ISSUE THREAD

**Issue by brendenyule** [rabbitmq/chef-cookbook#422]
When trying to set any policy through attributes, I am getting this error.

Here are the attributes I am trying to set:

  ```
default['rabbitmq']['policies']['mps-ha-all']['pattern'] = '^'
  default['rabbitmq']['policies']['mps-ha-all']['params'] = { 'ha-mode':  'all', "ha-sync-mode": "automatic" }
  default['rabbitmq']['policies']['mps-ha-all']['priority'] = 0
```

**Comment by brendenyule** [comment]
It looks like there are strings being appended to a frozen string: https://github.com/rabbitmq/chef-cookbook/blob/master/providers/policy.rb#L29

**Comment by michaelklishin** [comment]
Feel free to look into a PR. And also please post full stack traces when reporting issues in the future (here and everywhere else).

**Comment by brendenyule** [comment]
Stack Trace
`52.204.64.170     ================================================================================
52.204.64.170     Error executing action `set` on resource 'rabbitmq_policy[mps-ha-all]'
52.204.64.170     ================================================================================
52.204.64.170
52.204.64.170     RuntimeError
52.204.64.170     ------------
52.204.64.170     can't modify frozen String
52.204.64.170
52.204.64.170     Cookbook Trace:
52.204.64.170     ---------------
52.204.64.170     /var/chef/cache/cookbooks/rabbitmq/providers/policy.rb:31:in `policy_exists?'
52.204.64.170     /var/chef/cache/cookbooks/rabbitmq/providers/policy.rb:44:in `block in class_from_file'
52.204.64.170
52.204.64.170     Resource Declaration:
52.204.64.170     ---------------------
52.204.64.170     # In /var/chef/cache/cookbooks/rabbitmq/recipes/policy_management.rb
52.204.64.170
52.204.64.170      26:   rabbitmq_policy name do
52.204.64.170      27:     pattern policy['pattern']
52.204.64.170      28:     params policy['params']
52.204.64.170      29:     priority policy['priority']
52.204.64.170      30:     vhost policy['vhost']
52.204.64.170      31:     apply_to policy['apply_to']
52.204.64.170      32:     action :set
52.204.64.170      33:     notifies :restart, "service[#{node['rabbitmq']['service_name']}]"
52.204.64.170      34:   end
52.204.64.170      35: end
52.204.64.170
52.204.64.170     Compiled Resource:
52.204.64.170     ------------------
52.204.64.170     # Declared in /var/chef/cache/cookbooks/rabbitmq/recipes/policy_management.rb:26:in `block in from_file'
52.204.64.170
52.204.64.170     rabbitmq_policy("mps-ha-all") do
52.204.64.170       params {"ha-mode"=>"all", "ha-sync-mode"=>"automatic"}
52.204.64.170       action [:set]
52.204.64.170       retries 0
52.204.64.170       retry_delay 2
52.204.64.170       default_guard_interpreter :default
52.204.64.170       declared_type :rabbitmq_policy
52.204.64.170       cookbook_name "rabbitmq"
52.204.64.170       recipe_name "policy_management"
52.204.64.170       pattern "^"
52.204.64.170       priority 0
52.204.64.170     end
52.204.64.170
52.204.64.170     Platform:
52.204.64.170     ---------
52.204.64.170     x86_64-linux
52.204.64.170`

**Comment by michaelklishin** [comment]
It's not clear to me what may be freezing the string here:
https://github.com/rabbitmq/chef-cookbook/blob/master/providers/policy.rb#L29.

@jjasghar does anything stand out to you?

**Comment by brendenyule** [comment]
Yeah, the comment at the top of the page enables freezing by default. 
https://blog.lucascaton.com.br/2016/01/19/what-is-frozen_string_literal-in-ruby/

Looks like a recent PR added that comment to just about everything.

**Comment by brendenyule** [comment]
Basically all appends on that page should be broken now.

**Comment by michaelklishin** [comment]
Oh, I had no idea strings can be made frozen by default. I feel like it's a bit overreaching.
It was introduced in https://github.com/rabbitmq/chef-cookbook/commit/f9a90e984067443dcc64256b224ac064451de120, @jjasghar was that intentional?

**Comment by jjasghar** [comment]
With the standard rubocops that i'm using, yeah. 

I guess we'll need to extend the logic to fix this now. iirc it's in prep for Ruby 3.

**Comment by michaelklishin** [comment]
extend the logic where?

In Chef resources specifically it is very common to incrementally build a string. I am not aware of a way to "unfreeze" a string. This change will be a huge deal for Chef cookbooks.

**Comment by michaelklishin** [comment]
@jjasghar I don't know how far off Ruby 3.0 is but unless there's a recommended practice already I'd suggest unrolling those literals in most files.

**Comment by michaelklishin** [comment]
OK, I think I have found a [solution](https://github.com/rspec/rspec-core/pull/2268/files#diff-89a77987791b99dfc9d2e744919d0c42L854): `String#+` seems to produce a copy instead of modifying the receiver in place. It's easier demonstrated with an irb session:

```
2.3.1 :001 > s = "abc"
 => "abc"
2.3.1 :002 > s.freeze
 => "abc"
2.3.1 :003 > s << "1"
RuntimeError: can't modify frozen String
	from (irb):3
	from /Users/antares/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
2.3.1 :004 > s += "1"
 => "abc1"
```

So switching our code to use that style should work. @jjasghar @brendenyule how does that sound?

**Comment by brendenyule** [comment]
That makes sense to me. Seems like a good workaround, and is actually pretty useful to know.

**Comment by michaelklishin** [comment]
Unfortunately this will make the code look pretty weird (by Ruby standards, definitely not e.g. Erlang).

I vote for rolling back the tags, issuing a new patch release and then looking into the migration. As things stand right now, we sacrificed our users to Rubocop, which is backwards.

**Comment by michaelklishin** [comment]
So it's pretty confusing as to what's going on here:

```
2.3.1 :001 > s = "abc"
 => "abc"
2.3.1 :002 > s.freeze; s += "1"
 => "abc1"
2.3.1 :003 > s
 => "abc1"
2.3.1 :004 > s.frozen?
 => false
2.3.1 :005 > s.freeze
 => "abc1"
2.3.1 :006 > s.frozen?
 => true
2.3.1 :007 > s += "1"
 => "abc11"
2.3.1 :008 > s
 => "abc11"
2.3.1 :009 > s.frozen?
 => false
```

WAAAAAAT.

**Comment by michaelklishin** [comment]
Right, so `+=` doesn't mutate the value but it does re-assign the variable. Of course, this concept gets pretty foreign after a lot of time spent with Erlang :)

So if the goal is to prepare to the world with frozen strings by default, that'd do (and the code will look still like typical Ruby).

**Comment by michaelklishin** [comment]
@jjasghar so what would you like us to do, switch to using `+=` or undo the literal tag first and issue a quick patch release?

@brendenyule would you be interested in looking into a PR that replaces all `String<<`s with `+=` on string instances?

**Comment by brendenyule** [comment]
Sure, that is easy to do
