### ISSUE TITLE
policy provider prevents updating an existing policy

### ISSUE THREAD

**Issue by brendenyule** [rabbitmq/chef-cookbook#424]
The set action in policy provider prevents a policy from being set [if it already exists.](https://github.com/rabbitmq/chef-cookbook/blob/master/providers/policy.rb#L44)
I think expected behavior would be to let the policy be updated if it already exists.

`rabbitmqctl set_policy` is already an idempotent command and handles this out of the box.

Casual proof the `rabbitmq set_policy` is idempotent:
```
user@ip:~$ sudo rabbitmqctl list_policies
Listing policies ...
/	mps-ha-all	all	^	{"ha-mode":"all"}	0

user@ip:~$ sudo rabbitmqctl set_policy mps-ha-all "^" '{"ha-mode":"all"}' --priority 0
Setting policy "mps-ha-all" for pattern "^" to "{\"ha-mode\":\"all\"}" with priority "0" ...

user@ip:~$ sudo rabbitmqctl list_policies
Listing policies ...
/	mps-ha-all	all	^	{"ha-mode":"all"}	0
```

**Comment by michaelklishin** [comment]
Should be fixed in #425, thank you.
