### ISSUE TITLE
unable to set nofile ulimit on rhel

### ISSUE THREAD

**Issue by acranox** [rabbitmq/chef-cookbook#443]
attributes.rb is setting both these:

default['rabbitmq']['max_file_descriptors'] = 1024
default['rabbitmq']['open_file_limit'] = nil

/etc/default/rabbitmq-server is only being used by debian platforms:
https://github.com/rabbitmq/chef-cookbook/blob/master/templates/default/default.rabbitmq-server.erb

The code that actually does anything with the ulimit is inside a case statement that only applies to debian:
https://github.com/rabbitmq/chef-cookbook/blob/master/recipes/default.rb#L92-L97

I don't see a way to set the ulimit on RHEL platforms.  it certainly stopped working for me when i switched from cookbook version 4.10.0 to 4.12.1

**Comment by michaelklishin** [comment]
Arguably it's something you should do with the `ulimit` cookbook.

**Comment by michaelklishin** [comment]
This is greatly complicated by the fact that systemd has its own way of managing OS limits (how surprising, I know), and most recent Debian and Ubuntu releases use systemd.

Which is a yet another argument for a separate cookbook. @jjasghar WDYT?

**Comment by acranox** [comment]
in my case, I created a systemd override with the systemd cookbook.
but I got bit, because the functionality _used_ to be in this cookbook, and there's still attributes that imply it can do it, but they don't work on all platforms.  So it was a surprise.

```
+# Create a systemd override for rabbitmq
include_recipe 'systemd'

systemd_service 'rabbitmq-server' do
  drop_in true
  override 'rabbitmq-server'
  limit_nofile '8192'
end
```

**Comment by michaelklishin** [comment]
@acranox I understand. Unfortunately I think trying to support this feature in this cookbook is counterproductive and we should build on top of other cookbooks such as `systemd` and `ulimit`.
Would you agree?

**Comment by acranox** [comment]
That seems correct.  Setting ulimits should be handled outside of this cookbook.
