### ISSUE TITLE
Clarification of conf and additional_rabbit_configs attributes

### ISSUE THREAD

**Issue by adhodgson1** [rabbitmq/chef-cookbook#450]
Hi,

I want to add a section to the rabbitmq.conf file relating to the auto cluster plugin.  I initially thought I could add this to the additional_rabbit_configs node attribute, but looking at this further I don't believe it will work.

Is it best to override the config template in a wrapper cookbook rather than overriding this node attribute?

Thanks,
Andrew.

**Comment by michaelklishin** [comment]
`additional_rabbit_configs` expands arbitrary pairs in the `rabbit` "section" (application). `rabbitmq-autocluster` is a separate application ("section") and also uses nesting, so you have to use a wrapper or a way to inject arbitrary text into the config.

Starting with RabbitMQ 3.7.0 more things, including peer discovery (à la rabbitmq-autocluster), can use a [new ini-style config format](http://next.rabbitmq.com/configure.html) which can be generated with something similar to `additional_rabbit_configs`, plus there will be a separate config file for things that can't be.

This cookbook therefore will be able to accommodate more complex configurations without wrappers.

**Comment by michaelklishin** [comment]
Also, it's probably a typo but still: `rabbitmq.conf` does not exist in any released versions, only `3.7.0` milestones. You probably mean `rabbitmq.config`. `rabbitmq-env.conf` is a different file still used to set environment variable values.
