### ISSUE TITLE
Unable to Reset Node After Erlang Cookie Update

### ISSUE THREAD

**Issue by ryanhonrado** [rabbitmq/chef-cookbook#451]
Even after stopping the rabbit application, I am getting the error, 

```
Error: {failed_to_remove_node, NODE_ID@IP_ADDRESS} when trying to reset the node.

In addition, the following error occurs right after,
Error: {no_running_cluster_nodes,"You cannot leave a cluster if no online nodes are present."}

Below is the final error output(if that helps)
========================================================================= Error executing action `run` on resource 'execute[reset-node]'                                                                                               =========================================================================
                                                                                               
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '70'
---- Begin output of rabbitmqctl stop_app && rabbitmqctl reset && rabbitmqctl start_app ----
STDOUT: Stopping rabbit application on node 'NODE_ID'
Resetting node 'NODE_ID@IP_ADDRESS'
STDERR: Error: {no_running_cluster_nodes,"You cannot leave a cluster if no online nodes are present."}
---- End output of rabbitmqctl stop_app && rabbitmqctl reset && rabbitmqctl start_app ----
Ran rabbitmqctl stop_app && rabbitmqctl reset && rabbitmqctl start_app returned 70
```

Any suggestion would be greatly appreciated.

**Comment by michaelklishin** [comment]
All nodes must have the same cookie (for both effective server user and all users that use CLI tools).
Otherwise all `rabbitmqctl` commands will fail. This is not necessarily an indication of an issue in this cookbook.

`no_running_cluster_nodes` suggests that all cluster peers were not reachable at the time the reset was attempted.

I'm afraid I cannot recommend anything else with the amount of information provided.

**Comment by michaelklishin** [comment]
See [How Nodes and CLI Tools Authenticate to Each Other](http://www.rabbitmq.com/clustering.html).

**Comment by ryanhonrado** [comment]
Thanks for the advice. Not sure if this will help but let me expand the process on which the error occurred.
              
                                                                             
 - update content in file /var/lib/rabbitmq/.erlang.cookie from dae586 to a1a86f
 --- /var/lib/rabbitmq/.erlang.cookie     2017-07-07 00:00:00.000000000 +0000
+++ /var/lib/rabbitmq/.chef-.erlang.cookie20170707-2038-zeuvqg.erlang.cookie     
2017-07-07 20:55:30.186846000 +0000
@@ -1,2 +1,2 @@

[2017-07-07T20:55:30+00:00] INFO: template[/var/lib/rabbitmq/.erlang.cookie] sending start action to service[rabbitmq-server] (immediate)
* service[rabbitmq-server] action start[2017-07-07T20:55:30+00:00] INFO: Processing service[rabbitmq-server] action start (rabbitmq::default line 254)

[rabbitmq-clustered-2] [2017-07-07T20:55:34+00:00] INFO: service[rabbitmq-server] started
- start service service[rabbitmq-server]
[2017-07-07T20:55:34+00:00] INFO: template[/var/lib/rabbitmq/.erlang.cookie] sending run action to execute[reset-node] (immediate)
* execute[reset-node] action run[2017-07-07T20:55:34+00:00] INFO: Processing execute[reset-node] action run (rabbitmq::default line 245)

[rabbitmq-clustered-1] [2017-07-07T20:55:34+00:00] INFO: service[rabbitmq-server] started
- start service service[rabbitmq-server]
[2017-07-07T20:55:34+00:00] INFO: template[/var/lib/rabbitmq/.erlang.cookie] sending run action to execute[reset-node] (immediate)
* execute[reset-node] action run[2017-07-07T20:55:34+00:00] INFO: Processing execute[reset-node] action run (rabbitmq::default line 245)
   
[rabbitmq-clustered-2] 
[execute] Stopping rabbit application on node 'SOME_NODE@IP_ADD'

[rabbitmq-clustered-1] 
[execute] Stopping rabbit application on node 'SOME_NODE@IP_ADD1'

[rabbitmq-clustered-2]               
Resetting node 'SOME_NODE@IP_ADD2'

[rabbitmq-clustered-1]               
Resetting node 'SOME_NODE@IP_ADD1'
Error: {failed_to_remove_node,'SOME_NODE@IP_ADD1',
{no_exists,rabbit_vhost}}

[2017-07-07T20:55:36+00:00] INFO: Retrying execution of execute[reset-node], 11 attempt(s) left
[execute] Stopping rabbit application on node 'SOME_NODE@IP_ADD1'
Resetting node 'SOME_NODE@IP_ADD1'

[rabbitmq-clustered-2]               
Error: {no_running_cluster_nodes,"You cannot leave a cluster if no online nodes are present."}

[2017-07-07T20:55:42+00:00] INFO: Retrying execution of execute[reset-node], 11 attempt(s) left
[execute] Stopping rabbit application on node 'SOME_NODE@IP_ADD2'
Resetting node 'SOME_NODE@IP_ADD12'
Error: {no_running_cluster_nodes,"You cannot leave a cluster if no online nodes are present."}
