### ISSUE TITLE
RabbitMQ Start fails when I recreate a VM with same storage and run chef converge again 

### ISSUE THREAD

**Issue by amulyas** [rabbitmq/chef-cookbook#455]
RabbitMQ Start fails when I recreate a VM with same storage and run chef converge again  looking for how to handle this start when machine gets recreated ... 
also I did a PR for https://github.com/rabbitmq/chef-cookbook/pull/454
                                              ================================================================================
                                                                                               Error executing action `start` on resource 'service[rabbitmq-server]'
                                                                                               ================================================================================

                                                                                               Mixlib::ShellOut::ShellCommandFailed
                                                                                               ------------------------------------
                                                                                               Expected process to exit with [0], but received '1'
                                                                                               ---- Begin output of /etc/init.d/rabbitmq-server start ----
                                                                                               STDOUT: * Starting message broker rabbitmq-server
                                                                                                * FAILED - check /var/log/rabbitmq/startup_\{log, _err\}
                                                                                                  ...fail!
                                                                                               STDERR:
                                                                                               ---- End output of /etc/init.d/rabbitmq-server start ----
                                                                                               Ran /etc/init.d/rabbitmq-server start returned 1

from Rabbit Node Logs 
=INFO REPORT==== 3-Aug-2017::00:17:29 ===
node           : 09a1d76e-e4a3-4a32-b226-049d93b67d43@ip-10-72-87-174
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : yEmBvcD/asxKPa/1IyJNbw==
log            : /var/log/rabbitmq/09a1d76e-e4a3-4a32-b226-049d93b67d43.log
sasl log       : /var/log/rabbitmq/09a1d76e-e4a3-4a32-b226-049d93b67d43-sasl.log
database dir   : /var/lib/rabbitmq/mnesia/09a1d76e-e4a3-4a32-b226-049d93b67d43

=INFO REPORT==== 3-Aug-2017::00:17:30 ===
Memory limit set to 7185MB of 7984MB total.

=INFO REPORT==== 3-Aug-2017::00:17:30 ===
Enabling free disk space monitoring

=INFO REPORT==== 3-Aug-2017::00:17:30 ===
Disk free limit set to 50MB

=INFO REPORT==== 3-Aug-2017::00:17:30 ===
Limiting to approx 924 file handles (829 sockets)

=INFO REPORT==== 3-Aug-2017::00:17:30 ===
FHC read buffering:  OFF
FHC write buffering: ON

=INFO REPORT==== 3-Aug-2017::00:17:30 ===
Waiting for Mnesia tables for 30000 ms, 9 retries left

=WARNING REPORT==== 3-Aug-2017::00:18:04 ===
Error while waiting for Mnesia tables: {timeout_waiting_for_tables,
                                        [rabbit_user,rabbit_user_permission,
                                         rabbit_vhost,rabbit_durable_route,
                                         rabbit_durable_exchange,
                                         rabbit_runtime_parameters,
                                         rabbit_durable_queue]}

=INFO REPORT==== 3-Aug-2017::00:18:04 ===
Waiting for Mnesia tables for 30000 ms, 8 retries left

=WARNING REPORT==== 3-Aug-2017::00:18:34 ===
Error while waiting for Mnesia tables: {timeout_waiting_for_tables,
                                        [rabbit_user,rabbit_user_permission,
                                         rabbit_vhost,rabbit_durable_route,
                                         rabbit_durable_exchange,
                                         rabbit_runtime_parameters,
                                         rabbit_durable_queue]}

=INFO REPORT==== 3-Aug-2017::00:18:34 ===
Waiting for Mnesia tables for 30000 ms, 7 retries left

=WARNING REPORT==== 3-Aug-2017::00:19:03 ===
Error while waiting for Mnesia tables: {timeout_waiting_for_tables,
                                        [rabbit_user,rabbit_user_permission,
                                         rabbit_vhost,rabbit_durable_route,
                                         rabbit_durable_exchange,
                                         rabbit_runtime_parameters,
                                         rabbit_durable_queue]}

=INFO REPORT==== 3-Aug-2017::00:19:03 ===
Waiting for Mnesia tables for 30000 ms, 6 retries left

=CRASH REPORT==== 3-Aug-2017::00:17:18 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.138.0>
    registered_name: []
    exception exit: {{timeout_waiting_for_tables,
                         [rabbit_user,rabbit_user_permission,rabbit_vhost,
                          rabbit_durable_route,rabbit_durable_exchange,
                          rabbit_runtime_parameters,rabbit_durable_queue]},
                     {rabbit,start,[normal,[]]}}
      in function  application_master:init/4 (application_master.erl, line 133)
    ancestors: [<0.137.0>]
    messages: [{'EXIT',<0.139.0>,normal}]
    links: [<0.137.0>,<0.7.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 206
  neighbours:

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
@amulyas please consider posting questions to rabbitmq-users or Chef mailing list in the future.

`timeout_waiting_for_tables` means that a node could not contact a known peer to sync internal database from. Before RabbitMQ 3.6.7, there is only one timeout, [`rabbit. mnesia_table_loading_timeout`](https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq_v3_6_6/docs/rabbitmq.config.example#L310), which is 30 seconds by default.

Starting with 3.6.7, there are two settings:

 * [`rabbit.mnesia_table_loading_retry_limit`](https://github.com/rabbitmq/rabbitmq-server/blob/stable/docs/rabbitmq.config.example#L329), the number of retries, 10 by default
 * [`rabbit. mnesia_table_loading_retry_timeout`](https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq_v3_6_10/docs/rabbitmq.config.example#L310), a timeout per attempt, 30s by default.

We highly recommend upgrading to `3.6.10` and adjusting those two as needed in `rabbitmq.config`. 10 retries with a 30s timeout each is sufficient in most cases but 30s prior to 3.6.7 can be too low.

**Comment by amulyas** [comment]
@michaelklishin first of all thank you very much for your inputs .. the way we spin up 3 node cluster is bring up all three nodes at same time and run chef converge on all three in same time with auto clusturing on we make sure erlang cookie is same and all that stuff, and like 2 out of 5 times we run into this error.. on retry most of the time this error get solved and thats why I sent the PR .. we can bump up to 3.6.10 and see if that helps if not we will add these settings .. 

I have one more question do you think we should converge one node at a time or it is ok to converge all three at same time

**Comment by michaelklishin** [comment]
With 3.6.7+ you can do either, at least if initial peer discovery is not an issue because you specify all cluster members in the config file or use [rabbitmq-autocluster](https://github.com/rabbitmq/rabbitmq-autocluster).

**Comment by amulyas** [comment]
we are actually using 3.6.10

**Comment by michaelklishin** [comment]
Then no previously known peer shows up in 5 minutes in your case (which can be the case for the first node if you restart strictly sequentially). Try doing it all at once or at least one after another after a limited delay.

**Comment by michaelklishin** [comment]
I'm locking this because this is not a discussion venue.
