### ISSUE TITLE
sndbuf, recbuf and credit_flow_default_credit in config file

### ISSUE THREAD

**Issue by jennyfountain** [rabbitmq/chef-cookbook#459]
Are these going to be included in any updated releases?

**Comment by michaelklishin** [comment]
@jennyfountain what do you mean by "updated releases"? They will be included in the next release as soon as someone contributes them :) It should be a fairly small change, there are other `tcp_options` that are configurable, for example. Would you be interested in looking into a pull request? We'd be happy to offer some advice if you are not sure where to start.

**Comment by jennyfountain** [comment]
yes, yes I can contribute!

**Comment by michaelklishin** [comment]
This can be supported directly or as part of #442 once we switch to the new config format in 3.7.
