### ISSUE TITLE
Wrong quotes in additional_rabbit_configs for arrays

### ISSUE THREAD

**Issue by sekrett** [rabbitmq/chef-cookbook#461]
I am configuring PKI for RabbitMQ, I need to add the following to my attributes to make it work:

```ruby
default['rabbitmq']['additional_rabbit_configs'] = {
  'auth_mechanisms' => %w[EXTERNAL],
  'ssl_cert_login_from' => 'common_name'
}
```

I think for Erlang it is important to have single quotes. With double quotes in my config file I cannot establish the connection.

## Expected Behavior
```
,{auth_mechanisms, ['EXTERNAL']}
,{ssl_cert_login_from, common_name}
```

## Current Behavior
```
,{auth_mechanisms, ["EXTERNAL"]}
,{ssl_cert_login_from, common_name}
```
## Workaround
Put array inside the string:
```'auth_mechanisms' => "['EXTERNAL']"```

## Your Environment
* Version of this cookbook used: 5.2.0
* Version of Chef used: 12.20.3
* Operating System and version: Debian 8.9

**Comment by michaelklishin** [comment]
@sekrett single quotes in Erlang do not produce strings (they produce atoms), so it is important in some cases such as [rabbitmq-auth-mechanism-ssl](https://github.com/rabbitmq/rabbitmq-auth-
mechanism-ssl) but not universally.

I don't see `auth_mechanisms` being configured by this cookbook, therefore there isn't much to fix. We can add a documentation note/example for the aforementioned plugin; feel free to look into a pull request that does that.

**Comment by sekrett** [comment]
Atoms, ok, make sense. It uses atoms for options and strings for paths to keys for example. You cannot guess.
