### ISSUE TITLE
Time for a new release (5.3.0)?

### ISSUE THREAD

**Issue by Wing924** [rabbitmq/chef-cookbook#462]
Current version in supermarket is 5.2.0 but updated time is June 16, 2017.
I think we need to release new version and upload to supermarket.

**Comment by jjasghar** [comment]
I’ll get a release pushed out ASAP.

**Comment by jjasghar** [comment]
https://github.com/rabbitmq/chef-cookbook/blob/master/CHANGELOG.md#change-log :)
