### ISSUE TITLE
User management execution optimisation 

### ISSUE THREAD

**Issue by vladzu** [rabbitmq/chef-cookbook#463]
Hi, 
This is more an optimisation request not the bug. 
under providers/user.rb   there are functions like : 
def user_exists?(name)
def user_has_tag?(name, tag)

It executes rabbitmqctl -q list_users  on every user 2x times. 
If there are more than 10 users - this operation start to be time consuming.
The similar thing is with def user_has_permissions?(name, vhost, perm_list = nil)

Our proposal is to write  rabbitmqctl -q list_users  and rabbitmqctl -q list_user_permissions into buffer or temporary file and then use it for check. It should make all those checks much faster/

**Comment by michaelklishin** [comment]
@jjasghar is it common for resources to cache external tool output in modern Chef?

It's fairly unlikely to see 10s of thousands of users, so `rabbitmqctl list_users` output should be suitable for keeping in memory.

**Comment by vladzu** [comment]
Hi, 
So what is the decision ?

**Comment by michaelklishin** [comment]
I haven't heard from @jjasghar. Caching is something that always seems straightforward and almost always has unexpected side effects. If you need to create a lot of users and permissions, consider using [definitions import](http://www.rabbitmq.com/management.html) — improving support for which in this cookbook is definitely welcome.
