### ISSUE TITLE
.erlang.cookie template is not marked as sensitive

### ISSUE THREAD

**Issue by smekalayahoo** [rabbitmq/chef-cookbook#465]
The [recipe](https://github.com/rabbitmq/chef-cookbook/blob/master/recipes/default.rb#L255) doesnot mark the file as sensitive which logs the contents of the .erlang.cookie. 

Since the .erlang.cookie is a secret shared by the nodes in a cluster, it should be marked as sensitive.

**Comment by michaelklishin** [comment]
@smekalayahoo how do you suggest that the file is marked as sensitive? It has UNIX permissions of 0400. What is missing?

**Comment by smekalayahoo** [comment]
Right now, when we execute the recipe we find the .erlang.cookie value being logged in plain text. 
The below PR should prevent the value from being logged in clear text.
https://github.com/rabbitmq/chef-cookbook/pull/466

**Comment by michaelklishin** [comment]
Ah, so it's a Chef's `file` resource property. Makes sense!

**Comment by michaelklishin** [comment]
Thank you, #466 is in.

**Comment by smekalayahoo** [comment]
@michaelklishin Thanks, This was pretty fast

**Comment by michaelklishin** [comment]
@jjasghar do you think we can roll out a patch release with this? :)

**Comment by jjasghar** [comment]
Yep!

I'll get it out today.
