### ISSUE TITLE
rabbitmq not able to create user

### ISSUE THREAD

**Issue by ff-pjha** [rabbitmq/chef-cookbook#467]
Recipe: rabbitmq::default
         * directory[/var/lib/rabbitmq/mnesia] action create
           * cannot determine user id for 'rabbitmq', does the user exist on this system?
           ================================================================================
           Error executing action `create` on resource 'directory[/var/lib/rabbitmq/mnesia]'
           ================================================================================
           
           Chef::Exceptions::UserIDNotFound
           --------------------------------
           cannot determine user id for 'rabbitmq', does the user exist on this system?
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/rabbitmq/recipes/default.rb
           
           206: directory node['rabbitmq']['mnesiadir'] do
           207:   owner 'rabbitmq'
           208:   group 'rabbitmq'
           209:   mode '775'
           210:   recursive true
           211: end
           212: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/rabbitmq/recipes/default.rb:206:in `from_file'
           
           directory("/var/lib/rabbitmq/mnesia") do
             action [:create]
             default_guard_interpreter :default
             path "/var/lib/rabbitmq/mnesia"
             recursive true
             declared_type :directory
             cookbook_name "rabbitmq"
             recipe_name "default"
             owner "rabbitmq"
             group "rabbitmq"
             mode "775"
           end
           
           System Info:
           ------------
           chef_version=13.6.0
           platform=amazon
           platform_version=2017.03
           ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
           program_name=chef-client worker: ppid=3525;start=05:49:05;
           executable=/opt/chef/bin/chef-client
           
       
       Running handlers:
       [2017-11-01T05:49:11+00:00] ERROR: Running exception handlers
       [2017-11-01T05:49:11+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-11-01T05:49:11+00:00] ERROR: Exception handlers complete
       [2017-11-01T05:49:11+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 06 seconds
       [2017-11-01T05:49:11+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-11-01T05:49:11+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-11-01T05:49:11+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-11-01T05:49:11+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-11-01T05:49:11+00:00] ERROR: directory[/var/lib/rabbitmq/mnesia] (rabbitmq::default line 206) had an error: Chef::Exceptions::UserIDNotFound: cannot determine user id for 'rabbitmq', does the user exist on this system?
       [2017-11-01T05:49:11+00:00] ERROR: directory[/var/lib/rabbitmq/mnesia] (rabbitmq::default line 206) had an error: Chef::Exceptions::UserIDNotFound: cannot determine user id for 'rabbitmq', does the user exist on this system?
       [2017-11-01T05:49:11+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-11-01T05:49:11+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

I have overridden rabbitmq and erlang version as
default["rabbitmq"]["version"] = "3.6.12"
default["erlang"]["source"]["version"] = "20.1"
I am using amazon machine is equivalent to RHEL/centos 6

**Comment by ff-pjha** [comment]
Now if I pass the user from my cookbook 
user "rabbitmq"
Then it throws,
Recipe: sensu::rabbitmq
         * service[restart rabbitmq-server] action restart
           * service[restart rabbitmq-server]: No custom command for restart specified and unable to locate the init.d script!
           ================================================================================
           Error executing action `restart` on resource 'service[restart rabbitmq-server]'
           ================================================================================
           
           Chef::Exceptions::Service
           -------------------------
           service[restart rabbitmq-server]: No custom command for restart specified and unable to locate the init.d script!
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/sensu/recipes/rabbitmq.rb
           
            85: service "restart #{node["rabbitmq"]["service_name"]}" do
            86:   service_name node["rabbitmq"]["service_name"]
            87:   action :nothing
            88:   subscribes :restart, resources("template[#{node['rabbitmq']['config_root']}/rabbitmq.config]"), :immediately
            89: end
            90: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/sensu/recipes/rabbitmq.rb:85:in `from_file'
           
           service("restart rabbitmq-server") do
             action [:nothing]
             default_guard_interpreter :default
             service_name "rabbitmq-server"
             enabled nil
             running nil
             masked nil
             pattern "restart rabbitmq-server"
             declared_type :service
             cookbook_name "sensu"
             recipe_name "rabbitmq"
           end
           
           System Info:
           ------------
           chef_version=13.6.0
           platform=amazon
           platform_version=2017.03
           ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
           program_name=chef-client worker: ppid=3022;start=06:26:56;
           executable=/opt/chef/bin/chef-client

**Comment by michaelklishin** [comment]
[Answered on rabbitmq-users](https://groups.google.com/forum/#!searchin/rabbitmq-users/systemd%7Csort:date/rabbitmq-users/8IFYT9KTxmw/IgFDsa83BwAJ), no need to double post.

**Comment by ff-pjha** [comment]
Thank you for your response.
I haven't passed any rabbitmq version from my cookbook, so it's 3.6.12.
Now I have changed the url to 
default['rabbitmq']['rpm_package_url'] ='https://dl.bintray.com/rabbitmq/rabbitmq-server-rpm/'

after this it says rabbitmq user not present
cannot determine user id for 'rabbitmq', does the user exist on this system?

**Comment by ff-pjha** [comment]
And if I add the user, user "rabbitmq"
Then it throws restart of rabbitmq-server. Error same as above error, rabbitmq-server script not created in init.d.
