### ISSUE TITLE
Management SSL port in attributes.rb

### ISSUE THREAD

**Issue by adhodgson1** [rabbitmq/chef-cookbook#473]
Hi,

I don't believe this is correct in attributes.rb:

default['rabbitmq']['web_console_ssl_port'] = 15_671

I am using this currently and have overwritten this attribute in my wrapper cookbook.

Thanks.
Andrew.

**Comment by devsibwarra** [comment]
@adhodgson1 Based on the current code in master, changing that value _should_ change the management listener port

What Chef and rabbitmq/chef-cookbook versions are you using?
Can you provide the code you use in your wrapper cookbook to overwrite this value?
