### ISSUE TITLE
Cluster resource provider incorrectly determines node type?

### ISSUE THREAD

**Issue by pauldmccann** [rabbitmq/chef-cookbook#476]
Hi,
I believe there is an error on [line 259 of cluster.rb](https://github.com/rabbitmq/chef-cookbook/blob/master/providers/cluster.rb#L259) 

currently it is using the following to determine what the cluster node type should be:  
  var_cluster_node_type = parse_cluster_nodes_string(new_resource.cluster_nodes).each { |node| node['name'] == var_node_name }.first['type'] # ~FC039

I believe it should be using .select.   Right now, all nodes are using the nodetype of the first node in the list.
  var_cluster_node_type = parse_cluster_nodes_string(new_resource.cluster_nodes).each { |node| node['name'] == var_node_name }.first['type'] # ~FC039

**Comment by michaelklishin** [comment]
Yes, the `each` seems suspicious. Note that all nodes cannot be RAM ones, so this issue may be deeper that it seems.

**Comment by michaelklishin** [comment]
@pauldmccann so it's in the cluster node type change action. Please submit a PR that corrects it. It should be a lower risk change than I expected at first.

**Comment by pauldmccann** [comment]
Thanks Michael.   There should be a PR available now

**Comment by michaelklishin** [comment]
We believe #477 addressed this at least somewhat. The entire logic in that provider needs to be revisited.
