### ISSUE TITLE
Default rabbitmq version 3.6.15 and default Erlang version not compatible

### ISSUE THREAD

**Issue by electrawn** [rabbitmq/chef-cookbook#489]
Pivotal reports minimum erlang version for 3.6.15 is Erlang 19, default erlang version is attributes.rb is 16.

**Comment by michaelklishin** [comment]
Erlang is provisioned using the Erlang cookbook, which has its own defaults (and reason to use those defaults). Please file an issue with them.

3.6.15 does run on R16B03, even though it is not recommended. This cookbook provides examples that [demonstrate how to install Erlang 19.x or 20.x](https://github.com/rabbitmq/chef-cookbook#supported-rabbitmq-versions). I will extend the 3.6.x part to use 193.6 or similar.

**Comment by michaelklishin** [comment]
It's worth mentioning that in future versions RabbitMQ 3.6.x won't be supported at all and therefore it will be possible to potentially require OTP 19.3 or 20.x. But it'd be a controversial change and perhaps the Erlang cookbook should provision something more recent by default instead.

As much as we'd like to drop support for Erlang/OTP < 19.3 for 3.6.x, it can break upgrades for so many installations out there (especially when package pinning isn't used and the upgrade wasn't planned) that it will likely stay a claim in the docs.
