### ISSUE TITLE
How to install rabbitmq through chef?

### ISSUE THREAD

**Issue by dersar00** [rabbitmq/chef-cookbook#490]
Where I must set it? https://github.com/rabbitmq/chef-cookbook#set-rabbitmq-version-1
I add to my recipe `metadata.rb` file a `depends 'rabbitmq', '~> 5.6.1'`.
When I install rbenv/ruby/rails using `ruby_rbenv` cookboook I understand how it works. 
My cookbooks/my-cookbook/recipes/default.rb file( `depends 'ruby_rbenv', '~> 2.0.7'` also added to `metadata.rb` ): 

    RUBY_VERSION = '2.4.2'
        
    # Install Ruby, rbenv and make current version global
    rbenv_system_install 'system' 
    rbenv_user_install 'vagrant'
        
    rbenv_ruby RUBY_VERSION do
       user 'vagrant'
    end
        
    rbenv_plugin 'ruby-build' do
       git_url 'https://github.com/rbenv/ruby-build.git'
       user 'vagrant'
    end
        
    rbenv_global RUBY_VERSION do
       user 'vagrant'
    end
        
    # Install Bundler
    rbenv_gem 'bundler' do
    # version '1.15.4'
      user 'vagrant'
      rbenv_version RUBY_VERSION
    end
        
    # Install rails
    rbenv_gem 'rails' do
      user 'vagrant'
      rbenv_version RUBY_VERSION
    end
So, how I can do it?

**Comment by jjasghar** [comment]
You set the version via an attribute. https://docs.chef.io/attributes.html I would suggest going to https://learn.chef.io and start with the basics and then come to the rabbitmq cookbook when you are more comfortable with the chef ecosystem.
