### ISSUE TITLE
Cookbook tries to install Centos 7 package on Amazon Linux (Centos 6 derivative)

### ISSUE THREAD

**Issue by neil-greenwood** [rabbitmq/chef-cookbook#493]
## Expected Behaviour

Installing rabbitmq-server-3.6.12-1.el.noarch.rpm

## Actual Behaviour

Attempted to install rabbitmq-server-3.6.12-1.el7.noarch.rpm

* Cookbook version used
  5.6.1
* Operating system, version, and patch level
  Amazon Linux, 2017.09.1
* Node attributes
  normal['rabbitmq']['manage_service'] = false
  normal['rabbitmq']['version'] = '3.6.12'
  normal['rabbitmq']['cluster'] = true
  normal['rabbitmq']['erlang_cookie'] = 'REDACTED'
  normal['rabbitmq']['enabled_plugins'] = ['rabbitmq_federation','rabbitmq_federation_management']
* RabbitMQ version provisioned
  3.6.12
* Erlang version provisioned
  18.3
* RabbitMQ server and client application log files
  It didn't install, so there aren't any
* Brief instructions that can be used to reproduce the issue e.g. with Vagrant and `chef-solo`
  chef-solo 12.1.2 used with packer, amazon-ebs builder

```
  * remote_file[/var/chef/cache/rabbitmq-server-3.6.12-1.el7.noarch.rpm] action create_if_missing
    - create new file /var/chef/cache/rabbitmq-server-3.6.12-1.el7.noarch.rpm
    - update content in file /var/chef/cache/rabbitmq-server-3.6.12-1.el7.noarch.rpm from none to e8b48a
    (new content is binary, diff output suppressed)
  * rpm_package[/var/chef/cache/rabbitmq-server-3.6.12-1.el7.noarch.rpm] action install

    ================================================================================
    Error executing action `install` on resource 'rpm_package[/var/chef/cache/rabbitmq-server-3.6.12-1.el7.noarch.rpm]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of rpm  -i /var/chef/cache/rabbitmq-server-3.6.12-1.el7.noarch.rpm ----
    STDOUT:
    STDERR: warning: /var/chef/cache/rabbitmq-server-3.6.12-1.el7.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 6026dfca: NOKEY
    error: Failed dependencies:
    	systemd is needed by rabbitmq-server-3.6.12-1.el7.noarch
    ---- End output of rpm  -i /var/chef/cache/rabbitmq-server-3.6.12-1.el7.noarch.rpm ----
    Ran rpm  -i /var/chef/cache/rabbitmq-server-3.6.12-1.el7.noarch.rpm returned 1
```

```
$ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
$ cat /etc/lsb-release
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
```

**Comment by michaelklishin** [comment]
Feel free to submit a PR.

**Comment by michaelklishin** [comment]
It's [already possible to provision](https://github.com/rabbitmq/chef-cookbook#custom-package-download-locations) any RPM by overriding `node['rabbitmq']['rpm_package']` and `node['rabbitmq']['rpm_package_url']`, something like

``` ruby
node['rabbitmq']['rpm_package'] = "rabbitmq-server-3.6.16-1.el6.noarch.rpm""
# note: 3.7.x packages are downloaded from Bintray by default and use a different tagging scheme
node['rabbitmq']['rpm_package_url'] = "https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_16"

```

but a more suitable [default package name for Amazon Linux](https://github.com/rabbitmq/chef-cookbook/blob/84bfa21d3a84fa130458020485819270790167f9/recipes/default.rb#L44) is definitely something we'd welcome.

On an unrelated note, 3.6.12 is 4 releases behind even in the now EOL 3.6.x series, and Erlang/OTP 18.3 has [known catastrophic bugs](http://www.rabbitmq.com/which-erlang.html) that prevent nodes from accepting any TCP connections and shutting down.

**Comment by neil-greenwood** [comment]
@michaelklishin thanks for the comments about the out-of-date versions. During the work to resolve that, I found this bug. :)

**Comment by neil-greenwood** [comment]
I just managed to work around the issues I was having running the rspec tests, and I find you have put together a PR already.

I'll test it today.

**Comment by michaelklishin** [comment]
Leaving relevant links for my future self here:

 * Dokken image that provides [Amazon Linux 1](https://github.com/someara/dokken-images/blob/master/amazonlinux/Dockerfile)
 * Official [Amazon Linux 2 image](https://hub.docker.com/_/amazonlinux)

**Comment by michaelklishin** [comment]
Closing in favor of #515 which chooses to only support Amazon Linux 2.
