### ISSUE TITLE
Where to place RABBITMQ_USE_LONGNAME or other additional configs.

### ISSUE THREAD

**Issue by BMonsalvatge** [rabbitmq/chef-cookbook#499]
* Cookbook version used
`5.6.1`
* Operating system, version, and patch level
`Ubuntu 18.04`
* Node attributes
```ruby
default['rabbitmq']['version'] = '3.7.7'
default['rabbitmq']['clustering']['enable'] = true
default['rabbitmq']['clustering']['use_auto_clustering'] = false
default['rabbitmq']['server_additional_erl_args'] = {'RABBITMQ_USE_LONGNAME' => true}
default['rabbitmq']['clustering']['cluster_name'] = node['company']['environment']
default['rabbitmq']['clustering']['cluster_nodes'] = [
    {
        :name => "rabbit@rabbitmq-1.#{node['company']['environment']}.company.tld",
        :type => 'disc'
    },
    {
        :name => "rabbit@rabbitmq-2.#{node['company']['environment']}.company.tld",
        :type => 'disc'
    }
]
```
* RabbitMQ version provisioned
`3.7.7`

Currently I am looking for a way to include `RABBITMQ_USE_LONGNAME = true` to the rabbitmq configuration in order to use fqdn's for clustering: https://www.rabbitmq.com/clustering.html#hostname-resolution-requirement

I've tried adding `default['rabbitmq']['additional_rabbit_configs'] = {'RABBITMQ_USE_LONGNAME' => true}` to my cookbooks `attributes.rb` which causes the service restart to fail:

```   ================================================================================
    Error executing action `restart` on resource 'service[rabbitmq-server]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /bin/systemctl --system restart rabbitmq-server ----
    STDOUT: 
    STDERR: Job for rabbitmq-server.service failed because the control process exited with error code.
    See "systemctl status rabbitmq-server.service" and "journalctl -xe" for details.
    ---- End output of /bin/systemctl --system restart rabbitmq-server ----
    Ran /bin/systemctl --system restart rabbitmq-server returned 1
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/rabbitmq/recipes/default.rb
    
    291:   service node['rabbitmq']['service_name'] do
    292:     retries node['rabbitmq']['retry']
    293:     retry_delay node['rabbitmq']['retry_delay']
    294:     action [:enable, :start]
    295:     supports :status => true, :restart => true
    296:     provider Chef::Provider::Service::Upstart if node['rabbitmq']['job_control'] == 'upstart'
    297:     provider Chef::Provider::Service::Init if node['rabbitmq']['job_control'] == 'init'
    298:   end
    299: else
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/rabbitmq/recipes/default.rb:291:in `from_file'
    
    service("rabbitmq-server") do
      action [:enable, :start]
      supports {:status=>true, :restart=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "rabbitmq-server"
      enabled true
      running true
      masked false
      pattern "rabbitmq-server"
      declared_type :service
      cookbook_name "rabbitmq"
      recipe_name "default"
    end
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Additional configuration lines are for the config file. Environment variables are managed however you please, the cookbook only makes sure that `rabbitmq-env.conf` exists and is owned by `root`.

[RabbitMQ documentation](http://www.rabbitmq.com/configure.html) explains how to configure a node. This cookbook exposes some of the configuration in the [Chef] node attributes. Some ot
