### ISSUE TITLE
Downloaded community plugin is not unzipped

### ISSUE THREAD

**Issue by baltar** [rabbitmq/chef-cookbook#502]
* Cookbook version 5.6.1
* Ubuntu 14.04 LTS
* RabbitMQ version 3.7.8
* Erlang/OTP 21 

I'm trying to use the `rabbitmq::community_plugins` recipe to install the `rabbitmq_delayed_message_exchange`, giving this node attribute:
```
node.default['rabbitmq']['community_plugins']['rabbitmq_delayed_message_exchange'] = 'https://dl.bintray.com/rabbitmq/community-plugins/3.7.x/rabbitmq_delayed_message_exchange/rabbitmq_delayed_message_exchange-20171201-3.7.x.zip'
```

It does download the plugin and puts it into the `/usr/lib/rabbitmq/lib/rabbitmq_server-3.7.8/plugins` directory, but it just renames it to `rabbitmq_delayed_message_exchange.ez` instead of unzipping it. 

Chef outputs
```
    * execute[rabbitmq-plugins enable rabbitmq_delayed_message_exchange] action run[2018-12-07T09:29:17+03:00] INFO: Processing execute[rabbitmq-plugins enable rabbitmq_delayed_message_exchange] action run (/vagrant/local-deploy/.chef/local-mode-cache/cache/cookbooks/rabbitmq/providers/plugin.rb line 38)

      [execute] Error:
                {:plugins_not_found, [:rabbitmq_delayed_message_exchange]}
[2018-12-07T09:29:21+03:00] INFO: execute[rabbitmq-plugins enable rabbitmq_delayed_message_exchange] ran successfully
      - execute rabbitmq-plugins enable rabbitmq_delayed_message_exchange
  ```

So even though an error is logged that the plugin is not found, it still says "execute[rabbitmq-plugins enable rabbitmq_delayed_message_exchange] ran successfully". 

After chef then finishes wrongfully successfully, I can `unzip rabbitmq_delayed_message_exchange.ez` in the plugins directory and enable the plugin manually.

**Comment by michaelklishin** [comment]
It is not meant to be unzipped. RabbitMQ will expand plugins [during boot](http://www.rabbitmq.com/plugins.html).

**Comment by michaelklishin** [comment]
RabbitMQ plugins *are* distributed and installed as `.ez` files. Neither Chef nor the operator are expected to uncompress them. There can be other reasons for the message:

 * Your Erlang version is old and doesn't support code loading from archives
 * Installation path doesn't match the plugin directory actually used by the node
 * Plugin and broker version incompatibility
 * Plugin and Erlang version incompatibility

and so on. See server logs for more clues.

This is mailing list material.

**Comment by baltar** [comment]
All the community plugin files linked from https://www.rabbitmq.com/community-plugins.html are zip files. And as mentioned, when I manually unzip and enable it, it works, so tis has nothing to do worth version incompatibilities or plugin directory location. 

So the current approach simply _does not work_.  Please re-open this.

**Comment by michaelklishin** [comment]
So this is specific to downloads from that particular page. The download is an `.ez` file (which is a zip archive) inside a `.zip` archive.

**Comment by michaelklishin** [comment]
So when the downloaded file is a `.zip` archive, it should be possible to extract it. The same can be done for compressed tarballs. When it's an `.ez` file it should left intact.

There are two relevant cookbooks here:

 * [tar](https://supermarket.chef.io/cookbooks/tar)
 * [zip](https://supermarket.chef.io/cookbooks/zip)

I will try to take a look at this this weekend but make no promises. It should be a reasonably change, so PRs are welcome.

**Comment by baltar** [comment]
> So this is specific to downloads from that particular page. 

Yes. I get that community plugins are independent or RabbitMQ, but this page calls itself the "community plugin archive". So I would guess it's the main entry point for people looking for community plugins? Thanks for considering looking into it. I'll see if I can make a PR.
