### ISSUE TITLE
5.6.2 generates config file path with `.config` at the end which RabbitMQ 3.6.x does not support

### ISSUE THREAD

**Issue by craigjamesstewart** [rabbitmq/chef-cookbook#506]
Thank you for using RabbitMQ and for taking the time to report an
issue.

## Does This Belong to GitHub or RabbitMQ Mailing List?

*Important:* please first read the `CONTRIBUTING.md` document in the
root of this repository. It will help you determine whether your
feedback should be directed to the RabbitMQ mailing list [1] instead.

## Please Help Maintainers and Contributors Help You

In order for the RabbitMQ team to investigate your issue, please provide
**as much as possible** of the following details:

* Cookbook version used
5.6.2
* Operating system, version, and patch level
CentOS Linux release 7.6.1810 (Core)
* Node attributes
* RabbitMQ version provisioned
RabbitMQ 3.6.6
* Erlang version provisioned
Erlang 19.3.6.9
* RabbitMQ server and client application log files
Relevant lines from logs
=INFO REPORT==== 4-Mar-2019::15:50:28 ===                                                                                                                  
node           : {servername redacted}@{servername redacted}                                                                                                             
home dir       : /var/lib/rabbitmq                                     
config file(s) : /etc/rabbitmq/rabbitmq.config (not found)                                                                                                 
cookie hash    : REDACTED                                                                                                                     
log            : /opt/rabbitmq/logs/{servername redacted}.log
sasl log       : /opt/rabbitmq/logs/{servername redacted}-sasl.log        
database dir   : /opt/rabbitmq/mnesia/{servername redacted}
* Brief instructions that can be used to reproduce the issue e.g. with Vagrant and `chef-solo`
Deploy rabbitMQ version 3.6.6 using cookbook version 5.6.1 And working for remote connections
Run chef using cookbook version 5.6.2 and watch rabbitMQ stop accepting connections.

This information **greatly speeds up issue investigation** (or makes it
possible to investigate it at all). Please help project maintainers and
contributors to help you by providing it!

1. https://groups.google.com/forum/#!forum/rabbitmq-users
2. https://github.com/rabbitmq/support-tools/blob/master/scripts/rabbitmq-collect-env

**Comment by michaelklishin** [comment]
@craigjamesstewart I'm afraid there isn't much information to work with. Please provide steps to reproduce or at least any errors and config file entries generated (the logs says that the file does not exist at all).

Also note that RabbitMQ 3.6.x has been out of support for 9 months. In that series alone, `3.6.6` is 10 patch releases behind.

**Comment by craigjamesstewart** [comment]
Yes the error says the config file doesn't exist, but it does. The same line appears (without the "not found" part) when starting rabbitMQ after running chef using cookbook version 5.6.1

The only RabbitMQ related change between versions 5.6.2 of the cookbook and 5.6.1 was to /etc/rabbitmq/rabbitmq-env.conf and the change was
8c8                                                                                                                                                                                                                                                   
< CONFIG_FILE=/etc/rabbitmq/rabbitmq                                                                                                                                                                                      
---                                                                                                                                                                                                                        
> CONFIG_FILE=/etc/rabbitmq/rabbitmq.config

Your own docs state in the "Supported RabbitMQ Versions" at https://supermarket.chef.io/cookbooks/rabbitmq/versions/5.6.2 that you support using this cookbook for versions 3.7.x 3.6.x and even 3.5.x. However https://github.com/rabbitmq/chef-cookbook/pull/505 appears to have broken this, and you have released it as a patch level change, not a breaking change. However for 3.6.x branches of RabbitMQ it is a breaking change.

**Comment by michaelklishin** [comment]
@craigjamesstewart thanks for the details, now that's something actionable. I'm afraid supporting all 17 `3.6.x` patch releases plus 13 `3.7.x` patch releases is a bit tricky.

Another issue for `3.6.x` is the fact that `rabbitmq-plugins` commands do not support `-q`:

```
==> default: ---- Begin output of rabbitmq-plugins list -q -e 'rabbitmq_management\b' ----
==> default: STDOUT:
==> default: STDERR: Error: {'EXIT',
==> default:            {function_clause,
==> default:                [{rabbit_plugins_main,action,
==> default:                     [list,rabbit@vagrant,
==> default:                      ["-q","rabbitmq_management\\b"],
```

I'm looking into both things right now.

**Comment by michaelklishin** [comment]
There's now an InSpec suite for 3.6.16 as well as a [3.6.16 Vagrant example](https://github.com/rabbitmq/chef-cookbook-examples).
