### ISSUE TITLE
Use of node['lsb'] causes failures on non-Linux hosts

### ISSUE THREAD

**Issue by tas50** [rabbitmq/chef-cookbook#510]
Hi there. We use the rabbitmq cookbook thoughout our build / test environment at chef. Due to that the cookbook exists as a dep on a lot of non-Linux nodes even if it doesn't run. The 5.7.0 version of the cookbook includes the following line in the attributes file that causes a failure.

```ruby
default['rabbitmq']['erlang']['apt']['lsb_codename'] = node['lsb']['codename']
```

The problem is outside of Linux systems node['lsb'] doesn't exist so this results in a NilClass failure.

**Comment by tas50** [comment]
I just realized this was already fixed. NM

**Comment by michaelklishin** [comment]
Duplicate of #507.
