### ISSUE TITLE
Service is not known to chkconfig.

### ISSUE THREAD

**Issue by dannygueta** [rabbitmq/chef-cookbook#514]
Hi,

trying to deploy rabbitmq using this cookbook but from some reason it keeps failing.

using latest cookbook version (5.7.4) on Amazon Linux 2 (also tried regular amazon linux), running with Chef 13.12.14.

my run list is quite simple:

      "recipe[rabbitmq::erlang_package]"
      "recipe[rabbitmq::default]"

and my node params are:

 "rabbitmq":{
       "version": "3.6.15",
       "erlang":{
         "enabled":"true",
         "version": "20.3.8.20"
       }

first run fails due to missing rabbitmq user: 

    Error executing action `create` on resource 'directory[/var/lib/rabbitmq/mnesia]'
    Chef::Exceptions::UserIDNotFound
    --------------------------------
    cannot determine user id for 'rabbitmq', does the user exist on this system?

If i setup the user the 2nd run fails on:

```
service[rabbitmq-server] action enable
    * service[rabbitmq-server]: Service is not known to chkconfig.
    Error executing action `enable` on resource 'service[rabbitmq-server]'
```

any tip on what am i doing wrong would be greatly appreciated.

Thanks!

**Comment by michaelklishin** [comment]
Amazon Linux requires special casing compared to other RPM distributions. We don't run Test Kitchen tests for it. Googling for the serving message brings up a number of similar questions, all seemingly for Amazon Linux or CentOS 6 (the latter is covered by Test Kitchen).

I'm afraid I don't have the cycles for Amazon Linux and RabbitMQ 3.6 (which has been out of support for 10 months now).

You are welcome to submit PRs but I cannot suggest much with this amount of information.
The user should be created by the RPM package but a PR that creates it explicitly in `rabbitmq::default` would be welcome.

**Comment by michaelklishin** [comment]
I wonder if the behavior is due to https://github.com/rabbitmq/chef-cookbook/issues/493, which I will address in `v5.x` if Test Kitchen against Amazon Linux turns out to be reasonably easy to do. So far I only could find a [Dokken image for Amazon Linux 1](https://github.com/someara/dokken-images/tree/master/amazonlinux).

**Comment by michaelklishin** [comment]
Moved to #515.
