### ISSUE TITLE
Support for RabbitMQ 3.7 on Amazon Linux 2

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/chef-cookbook#515]
See #514 and #493. It would be nice to support at least latest versions of Amazon Linux 2 (in combination with supported RabbitMQ release series).

Some initial findings:

 * RabbitMQ zero dependency Erlang RPM for CentOS 7 installs and seem to be functional on AL2
 * RabbitMQ CentOS 7 package seem to be functional
 * There doesn't seem to be an ESL Erlang package for AL2 (they also don't have one for Fedora)

**Comment by michaelklishin** [comment]
Erlang cookbook doesn't support AL2 besides building from source. `recipe[rabbitmq_erlang]` is therefore going to be required. I have a passing test suite.

**Comment by michaelklishin** [comment]
@dannygueta not sure if this combination is an option for you but I will push Amazon Linux 2 support tested with RabbitMQ 3.7.13 packages. Since 3.6.15 is out of support, perhaps you can run this combination? You very likely won't have to update your clients.

**Comment by dannygueta** [comment]
@michaelklishin would definably help, thanks!

**Comment by michaelklishin** [comment]
@dannygueta with a bit of attribute massaging you can also run RabbitMQ 3.6 with the tip of `v5.x`. See [the 3.7 suite](https://github.com/rabbitmq/chef-cookbook/blob/v5.x/.kitchen.dokken.yml#L264) as well as [3.6 one](https://github.com/rabbitmq/chef-cookbook/blob/v5.x/.kitchen.dokken.yml#L280).
Provisioning Erlang was the biggest hurdle. It's good timing that we have LWRPs and a recipe to provision team RabbitMQ's zero dependency Erlang RPM.

Oh, and only Amazon Linux 2 is supported. Let me know how it goes.

**Comment by dannygueta** [comment]
@michaelklishin did a quick test, seems to work like a charm, thanks 👍
