### ISSUE TITLE
Erlang package installation from Bintray fails with undefined method `split' for ["-y"]:Array on Chef 12

### ISSUE THREAD

**Issue by IAPOLINARIO** [rabbitmq/chef-cookbook#522]
* Cookbook version used
5.7.6
* Operating system, version
CentOS Linux release 7.6.1810 (Core)
* RabbitMQ version provisioned
3.7
* Erlang version provisioned
21.3
* Attribute values 
Default

* Brief instructions that can be used to reproduce the issue 
Run the chef-client in a fresh CentOS node.

Error log: 

```
================================================================================
      Error executing action `install` on resource 'yum_package[rabbitmq_erlang]'
      ================================================================================

      NoMethodError
      -------------
      undefined method `split' for ["-y"]:Array

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/rabbitmq/providers/erlang_package_from_bintray.rb

       80:     package new_resource.name do
       81:       package_name 'erlang'
       82:       version new_resource.version unless new_resource.version.nil?
       83:       options %w(-y)
       84:       retries new_resource.retries
       85:       retry_delay new_resource.retry_delay unless new_resource.retry_delay.nil?
       86:     end
       87:   end

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/rabbitmq/providers/erlang_package_from_bintray.rb:80:in `block in class_from_file'

      yum_package("rabbitmq_erlang") do
        package_name "erlang"
        action [:install]
        retries 0
        retry_delay 10
        default_guard_interpreter :default
        declared_type :package
        cookbook_name "rabbitmq"
        version "1:21.3.3-1"
        flush_cache {:before=>false, :after=>false}
        options ["-y"]
      end

      Platform:
      ---------
      x86_64-linux

================================================================================
    Error executing action `install` on resource 'rabbitmq_erlang_package_from_bintray[rabbitmq_erlang]'
    ================================================================================

    NoMethodError
    -------------
    yum_package[rabbitmq_erlang] (/var/chef/cache/cookbooks/rabbitmq/providers/erlang_package_from_bintray.rb line 80) had an error: NoMethodError: undefined method `split' for ["-y"]:Array

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/rabbitmq/recipes/erlang_package.rb

     67:   rabbitmq_erlang_package_from_bintray 'rabbitmq_erlang' do
     68:     version erlang_version unless erlang_version.nil?
     69:
     70:     retry_delay node['rabbitmq']['erlang']['retry_delay'] unless node['rabbitmq']['erlang']['retry_delay'].nil?
     71:   end
     72: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/rabbitmq/recipes/erlang_package.rb:67:in `from_file'

    rabbitmq_erlang_package_from_bintray("rabbitmq_erlang") do
      action [:install]
      retries 0
      retry_delay 10
      default_guard_interpreter :default
      declared_type :rabbitmq_erlang_package_from_bintray
      cookbook_name "rabbitmq"
      recipe_name "erlang_package"
      version "1:21.3.3-1"
    end

    Platform:
    ---------
    x86_64-linux
```

**Comment by michaelklishin** [comment]
Test Kitchen tests cannot reproduce this. What Chef version is used?

**Comment by michaelklishin** [comment]
So looks like [`package` only accepts `options` as a string](https://docs.chef.io/resource_package.html) but `apt_package` accepts [both arrays and strings](https://docs.chef.io/resource_apt_package.html).

**Comment by IAPOLINARIO** [comment]
I'm using `Chef: 12.19.36`

**Comment by michaelklishin** [comment]
@Itxaka Chef 12 is [unsupported as of Feb 2019](https://blog.chef.io/2018/02/16/preparing-for-chef-14-and-chef-12-end-of-life/). 13.0 is 2 years old at this point. Changing to string options should work well with later versions and I'm OK with doing it if all tests pass but consider upgrading.

**Comment by IAPOLINARIO** [comment]
Metadata file just says: `chef_version '>= 12.0'`. So it should be compatible. Unfortunately, I can't upgrade my chef-client for now.

**Comment by michaelklishin** [comment]
@IAPOLINARIO this branch of the cookbook has been started several years ago. I strongly disagree that supporting Chef versions that Chef, Inc don't support is required from cookbook maintainers. Unfortunately bumping the metadata is a breaking change and a few Chef 12 users who do not use the same resource/recipe would complain.

**Comment by michaelklishin** [comment]
I will produce a patch release on this branch and move to 5.8 to not hear from hardcore semantic versioning fans. Chef 13 will be the minimum required version there.

**Comment by michaelklishin** [comment]
@IAPOLINARIO give the tip of `v5.x` a shot.

**Comment by IAPOLINARIO** [comment]
Thanks for your support @michaelklishin. 
Btw, I'm not a `hardcore semantic versioning fan`, I just pointed something that is present in the metadata file and can lead other people to some misinformation about the requirements as I did. I wouldn't mind upgrading my chef-client if I could.

**Comment by Itxaka** [comment]
Im not sure why I was mentioned here but if that means @michaelklishin has me in his mind, I can probably abuse that to request stuff in rabbitmq :P

**Comment by michaelklishin** [comment]
I did not mean anyone in particular and not going to debate semantic versioning or explain for the umteenth time why RabbitMQ cannot use it today (the reasons are not technical).

@IAPOLINARIO please give the tip a try so that I can produce a new release and put `5.7.x` and Chef 12 support to rest for good.

**Comment by IAPOLINARIO** [comment]
@michaelklishin It worked like a charm. :) 

Thanks.

**Comment by michaelklishin** [comment]
`5.7.7` is out, `v5.x` is now `5.8.0` and requires Chef 13.
