### ISSUE TITLE
cluster join

### ISSUE THREAD

**Issue by masikmos** [rabbitmq/chef-cookbook#534]
cookbook 6.0.0
ubuntu 18.04

```
join cluster
  * rabbitmq_cluster[5b094660f53f367ecc190e203f9a3bf10376c864] action join[2019-08-05T17:06:39+03:00] FATAL: rabbitmq_cluster with action :join requires a non-nil/empty cluster_nodes.
```

BUT! 
in attributes i have

```
override['rabbitmq']['clustering']['cluster_nodes'] = [
    {
        :name => 'rabbit@app01'
    },
    {
        :name => 'rabbit@app02'
    },
    {
        :name => 'rabbit@app03'
    }
]
```

and on chef web in attrebutes i see 

```
rabbitmq
default_user: blabla
default_pass: blabla
erlang_cookie: blablabla
clustering
enable: true
cluster_name: app_rabbitmq
cluster_nodes
0
name: rabbit@srv01
1
name: rabbit@srv02
2
name: rabbit@srv03
```

WHY non-nil/empty cluster_nodes. ??? HELP ME! )

**Comment by masikmos** [comment]
OMG.... how i got version 6.0.0 )))
o use berksfile and download from git latest and got 6.0.0

OOOPS Sry, move to 5.8.2 and looks good

**Comment by michaelklishin** [comment]
I don't see why master would be meaningfully different at the moment but there isn't much information to work with (sorry).

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/chef-cookbook/pull/238 was the last meaningful change around cluster member validation. The validation also seems to be [pretty basic](https://github.com/rabbitmq/chef-cookbook/blob/master/providers/cluster.rb#L197).

There are two mandatory properties for each node, though: `name` and `type` (the latter has to be set to `disc` for at least one, and for 99% of workloads all, of the nodes). That's my best as to what is off in your environment.
