### ISSUE TITLE
Don't edit policy-rc.d file

### ISSUE THREAD

**Issue by JanStevens** [rabbitmq/chef-cookbook#536]
## Versions

* Cookbook version used: v5.8.4
* Operating system, version, and patch level: Ubuntu 18.04 LTS
* Node attributes: N/A
* RabbitMQ version provisioned: 3.7.18
* Erlang version provisioned: esl 1:22.0.7-1
* RabbitMQ server and client application log files: N/A
* Brief instructions that can be used to reproduce the issue e.g. with Vagrant and `chef-solo`

If you have the official memcached cookbook and rabbitmq cookbook then depending on the order of the run list, they both edit policy-rc.d file. Which is a bit annoying

Related issue on memcached cookbook: https://github.com/chef-cookbooks/memcached/issues/97

**Comment by michaelklishin** [comment]
So what should we do instead and what risks would that entail?

**Comment by JanStevens** [comment]
A possible solution is to install the package, define a service stop and disable / remove it if needed

Not sure if there is another linux way. I'm also not sure if it matters that the service is started after install

**Comment by michaelklishin** [comment]
To disable/remove what, the service? That would violate user expectations in a major way.

This cookbook does not modify `policy-rc.d` file directly, unlike the [other one mentioned](https://github.com/chef-cookbooks/memcached/blob/470c9164c036d0d753c08641dfab2ea45f017abe/recipes/_package.rb#L23).

RabbitMQ Debian and RPM packages [do not modify the file either](https://github.com/rabbitmq/rabbitmq-server-release/search?q=policy-rc.d&unscoped_q=policy-rc.d).

So it must be one of the Chef resources used. Without Chef client logs or doing a repro run I have no idea what specifically it might be, likely `service`.

`policy-rc.d` seems to be specific to the System V `init` way of controlling certain aspects of service behavior. For better or worse, modern distributions have moved on to use `systemd`, which uses service-specific unit files (and this cookbook does produce a separate unit  file with a reasonable name).

If someone has the motivation to suggests a reasonable solution that does not involve removing the service or forcing the service to not be started after installation, let us know.

**Comment by JanStevens** [comment]
Yes this cookbook does change the dpkg settings

https://github.com/rabbitmq/chef-cookbook/blob/b609229ca012459d8d464cb3496868187cc157b7/recipes/default.rb#L87-L89

Which causes following output

```
* dpkg_autostart[bin_file] action create
vagrant     * template[dpkg_autostart_file] action create
vagrant       - update content in file /usr/sbin/policy-rc.d from c22995 to 13cff7
vagrant       --- /usr/sbin/policy-rc.d	2019-10-01 13:46:34.061836773 +0200
vagrant       +++ /usr/sbin/.chef-policy-rc20191001-1622-2gfkea.d	2019-10-01 13:46:36.793843047 +0200
vagrant       @@ -1,2 +1,83 @@
vagrant       -exit 0
vagrant       +#!/bin/bash
vagrant       +
vagrant       +DISABLE_ACTIONS=( start restart )
vagrant       +DISABLED_SERVICES=( rabbitmq-server )
vagrant       +
vagrant       +longoptions='quiet,force,try-anyway,disclose-deny,query,no-fallback,help'
vagrant       +getopt=$(getopt -o '' --longoptions $longoptions -- "$@")
vagrant       +if [ $? != 0 ]; then
vagrant       +   echo "ERROR!"
vagrant       +   exit 1;
vagrant       +fi
vagrant       +
vagrant       +eval set -- "$getopt"
vagrant       +
vagrant       +while true; do
vagrant       +      case "$1" in
vagrant       +      --quiet)
vagrant       +        QUIET=1
vagrant       +        shift
vagrant       +      ;;
vagrant       +      --force)
vagrant       +        FORCE=1
vagrant       +        shift
vagrant       +      ;;
vagrant       +      --try-anyway)
vagrant       +        TRY_ANYWAY=1
vagrant       +        shift
vagrant       +      ;;
vagrant       +      --disclose-deny)
vagrant       +        DISCLOSE_DENY=1
vagrant       +        shift
vagrant       +      ;;
vagrant       +      --query)
vagrant       +        QUERY=1
vagrant       +        shift
vagrant       +      ;;
vagrant       +      --no-fallback)
vagrant       +        NO_FALLBACK=1
vagrant       +        shift
vagrant       +      ;;
vagrant       +      --)
vagrant       +        shift
vagrant       +        break
vagrant       +      ;;
vagrant       +      *)
vagrant       +        echo "There should probably be some help text here!"
vagrant       +        exit 1
vagrant       +      ;;
vagrant       +      esac
vagrant       +done
vagrant       +
vagrant       +SRV_NAME=$1
vagrant       +shift
vagrant       +SRV_ACTION=$1
vagrant       +SRV_ARGS=$*
vagrant       +
vagrant       +SRV_DISABLED=0
vagrant       +ACT_DISABLED=0
vagrant       +
vagrant       +if [ ! -x "/etc/init.d/${SRV_NAME}" ] && [ ! -f "/etc/init/${SRV_NAME}.conf" ]; then
vagrant       +    exit 100
vagrant       +fi
vagrant       +
vagrant       +for i in "${DISABLED_SERVICES[@]}"
vagrant       +do
vagrant       +    if [ $i = $SRV_NAME ]; then
vagrant       +        SRV_DISABLED=1
vagrant       +    fi
vagrant       +done
vagrant       +
vagrant       +for i in "${DISABLE_ACTIONS[@]}"
vagrant       +do
vagrant       +    if [ $i = $SRV_ACTION ]; then
vagrant       +        ACT_DISABLED=1
vagrant       +    fi
vagrant       +done
vagrant       +
vagrant       +if [ $SRV_DISABLED -eq 1 -a $ACT_DISABLED -eq 1 ]; then
vagrant       +    exit 101
vagrant       +else
vagrant       +    exit 104
vagrant       +fi
vagrant      (up to date)
vagrant Recipe: rabbitmq::default
vagrant   * dpkg_autostart[rabbitmq-server] action nothing (skipped due to action :nothing)
vagrant   * remote_file[/var/chef/cache/rabbitmq-server_3.7.18-1_all.deb] action create_if_missing (up to date)
vagrant   * dpkg_package[rabbitmq-server] action upgrade (up to date)
vagrant   * directory[/var/lib/rabbitmq/mnesia] action create (up to date)
vagrant   * template[/etc/rabbitmq/rabbitmq-env.conf] action create (up to date)
vagrant   * template[/etc/rabbitmq/rabbitmq.config] action create (up to date)
vagrant   * template[/etc/default/rabbitmq-server] action create (up to date)
vagrant   * service[rabbitmq-server] action enable (up to date)
vagrant   * service[rabbitmq-server] action start (up to date)
vagrant   * ohai[reload_packages] action reload[2019-10-01T13:46:37+02:00] WARN: collect_data already defined on platform 'default' for Ohai::NamedPlugin::Nginx, last plugin seen will be used
vagrant
```

And indeed later on memcached overwrites this directly. I'm not saying rabbitmq cookbook should take action, just pointing out that one of the 2 cookbooks cause the issue of the changing file (since `dpkg_autostart` is used ill bug memcached cookbook)

**Comment by michaelklishin** [comment]
I see `dpkg_autostart` used in a number of other cookbooks maintained by the Chef, Inc  community. They do exactly the same thing without much explanation as to why.
