### ISSUE TITLE
Users management recipe does not manage tags

### ISSUE THREAD

**Issue by tophercullen** [rabbitmq/chef-cookbook#538]
For the default users recipe, tag management appears to be the only user attribute not actively managed by the default user management recipe. The 'set-tags' is only called when the user is first created, or the password is change. Only changing an existing user's tags doesn't actually apply those tag changes. 

This seems to be intentional, but its unclear to me why.

**Comment by michaelklishin** [comment]
@tophercullen I don't know if it's intentional but it can be revisited. Please submit a PR that demonstrates what you'd do?

**Comment by tophercullen** [comment]
This is what I mean by intentional https://github.com/rabbitmq/chef-cookbook/blob/v5.x/recipes/users.rb#L38

The PR is simple, I don't mind submitting it.
