### ISSUE TITLE
rabbitmq 3.8 new cluster_status cli output breaks cluster resource

### ISSUE THREAD

**Issue by jtschelling** [rabbitmq/chef-cookbook#548]
Cookbook version `5.8.4`
OS `Ubuntu 16`
RabbitMQ version `3.8.2`
Erlang version `22.1`

Relevant node attributes
```
$ knife node show staging-rabbit02.redacted.com -a rabbitmq
staging-rabbit02.redacted.com:
  rabbitmq:              
    clustering:
      cluster_name:               staging
      cluster_node_type:          disc
      cluster_nodes:
        name: rabbit@staging-rabbit01
        type: disc
        
        name: rabbit@staging-rabbit02
        type: disc
        
        name: rabbit@staging-rabbit03
        type: disc
```

-----------------------------------------

The `rabbitmqctl cluster_status` update in rabbitmq `3.8.x` broke this function's string parsing https://github.com/rabbitmq/chef-cookbook/blob/093331fab653dd9ac58fd105bbb4ef91f0657dfb/providers/cluster.rb#L47-L61

which means that this test for the node being in the cluster is never recognized https://github.com/rabbitmq/chef-cookbook/blob/093331fab653dd9ac58fd105bbb4ef91f0657dfb/providers/cluster.rb#L209

which means that the rabbitmq app is stopped every chef run and rejoins the cluster https://github.com/rabbitmq/chef-cookbook/blob/093331fab653dd9ac58fd105bbb4ef91f0657dfb/providers/cluster.rb#L217

I don't know if this means this cookbook should go through another major bump for rabbitmq `3.8` compatibility or not

**Comment by jtschelling** [comment]
this can be observed by running `sudo rabbitmqctl cluster_status` on a `3.7` rabbit node and then on a `3.8` node to see the output differences and why the string would not be parsed correctly

**Comment by lukebakken** [comment]
I suggest using the JSON formatter:

```
rabbitmqctl cluster_status --silent --formatter json
```

**Comment by michaelklishin** [comment]
@jtschelling we are quite aware of the changes. Are there examples of Chef resources that capture JSON output that you can recommend?

**Comment by jtschelling** [comment]
@lukebakken I know you know - hah - but just noting here that `3.7` and `3.8` both have the same `running_nodes` field that would be perfect for cross-compatibility here. Was that formatter flag introduced at some previous version of rabbit or there since the beginning? It seems like the best way to fix this, but if that json formatter flag was introduced at `3.6` or something there'd still be compatibility issues that would need to be denoted or code path changed in this cookbook

@michaelklishin since you're using the provider design pattern in this cookbook I'd probably just use the ruby core native json module

**Comment by lukebakken** [comment]
JSON formatting is supported since version `3.7.0`:

```
(20.3)lbakken@MESSIAEN ~/issues/rmq-generic-unix/rabbitmq_server-3.7.0
$ ./sbin/rabbitmqctl cluster_status --formatter json
{"nodes":{"disc":["rabbit@MESSIAEN"]},"running_nodes":["rabbit@MESSIAEN"],"cluster_name":"rabbit@localhost","partitions":[],"alarms":{"rabbit@MESSIAEN":[]}}
```

RabbitMQ 3.6 isn't supported anymore and the RMQ team does everything we can to discourage its use.

**Comment by jtschelling** [comment]
are you thinking divergent code paths based on running rabbit version or a major bump of this cookbook dropping RabbitMQ version `<3.7` support? I can put up a PR for this if you want, just wanna make sure i'm on the same page as you

**Comment by michaelklishin** [comment]
This cookbook's master has long dropped RabbitMQ 3.6 support and bumped the major version. That series has been out of support for 19 months in general. I would not mind dropping support for it in `v5.x` with a clear warning in the change log.
