### ISSUE TITLE
Incorrect config file path when deploying Rabbit 3.6.x

### ISSUE THREAD

**Issue by aprice** [rabbitmq/chef-cookbook#564]
* Cookbook version used: 5.8.4
* Operating system, version, and patch level: Ubuntu 18.04
* RabbitMQ version provisioned: 3.6.16
* Erlang version provisioned: 20.3

Due to [the default config file path](https://github.com/rabbitmq/chef-cookbook/blob/v5.x/attributes/default.rb#L64) and the [config file path helper](https://github.com/rabbitmq/chef-cookbook/blob/v5.x/libraries/default.rb#L86), the cookbook saves the config file as `/etc/rabbitmq/rabbitmq` by default rather than `/etc/rabbitmq/rabbitmq.conf` for deployments of RabbitMQ v3.6.x.

**Comment by michaelklishin** [comment]
Which is actually the correct thing to do: RabbitMQ 3.6 does not support the new style config format and IIRC does not support config file paths with the `.config` extension.

In other news, 3.6 has been out of support for [over two years](https://www.rabbitmq.com/versions.html).

**Comment by aprice** [comment]
"In other news" the cookbook starts off with:

> This is a cookbook for managing RabbitMQ with Chef. It is intended for RabbitMQ 2.6.1 or later releases.

Nice attitude toward your own community though.

**Comment by michaelklishin** [comment]
@aprice I'm sorry that my response seemed harsh to you.

I don't see [any mentions the quoted line in this repository](https://github.com/rabbitmq/chef-cookbook/search?q=intended&unscoped_q=intended) or on the [Chef Supermarket page](https://supermarket.chef.io/cookbooks/rabbitmq). 
There should be no references to 3.6 in any of the examples or even tests.

Please clarify where you are getting this from?

**Comment by michaelklishin** [comment]
Here is what the README says at the moment. The section on supported RabbitMQ series was a little further down before
(this can be seen on the Supermarket page) but nonetheless, no mentions of 2.6.1 or even 3.6.x:

<img width="935" alt="Chef RabbitMQ cookbook README supported versions" src="https://user-images.githubusercontent.com/1090/89893830-c0621780-dbe1-11ea-9f4a-dc1454ff590f.png">

Let me know what can be clarified further, or where.

RabbitMQ 3.6 releases can still be provisioned but all documentation
targets 3.8 (and except for features such as quorum queues or feature flags, this generally applies to `3.7.27`), both for [RabbitMQ itself](https://www.rabbitmq.com/configure.html) or this cookbook.
