### ISSUE TITLE
Socat RPM for CentOS 6 is no longer available

### ISSUE THREAD

**Issue by t-adachi** [rabbitmq/chef-cookbook#567]
I download socat-1.7.2.3-1.el6.x86_64.rpm with the default recipe, but it doesn't work with HTTP status 403.

https://kojipkgs.fedoraproject.org//packages/socat/1.7.2.3/1.el6/x86_64/socat-1.7.2.3-1.el6.x86_64.rpm

https://github.com/rabbitmq/chef-cookbook/blob/v5.x/recipes/default.rb#L197
https://github.com/rabbitmq/chef-cookbook/blob/v5.x/attributes/default.rb#L34-L35

Is there a way around this situation?

**Comment by michaelklishin** [comment]
CentOS 6 repositories have gone offline because CentOS 6 has reached EOL. If this file is downloaded from a CentOS 6 repo for other versions, please submit a PR that switches to a CentOS 7 location. Otherwise, this cookbook cannot realistically support CentOS 6 when the CentOS community itself does not.

**Comment by michaelklishin** [comment]
Switching [this line](https://github.com/rabbitmq/chef-cookbook/blob/v5.x/attributes/default.rb#L34-L35) to use https://kojipkgs.fedoraproject.org//packages/socat/1.7.2.3/1.fc20/x86_64/ should address it. I have not tried using this version but it is from 2014, so CentOS 7 should be covered. I am not sure about CentOS 8.

We would consider other locations, of course, if there are any.

**Comment by t-adachi** [comment]
thanks you.
Once, I was able to avoid it by making the recipe the following contents.

```
node.default['rabbitmq']['socat_package'] = 'socat-1.7.2.3-1.fc20.x86_64.rpm'
node.default['rabbitmq']['socat_package_url'] = 'https://kojipkgs.fedoraproject.org//packages/socat/1.7.2.3/1.fc20/x86_64/'
```

**Comment by michaelklishin** [comment]
Thanks for sharing the alternative download location. This cookbook has moved on from CentOS 6 support as both CentOS/Red Hat and RabbitMQ no longer support that version.
