### ISSUE TITLE
Bintray deprecation

### ISSUE THREAD

**Issue by mmiller1** [rabbitmq/chef-cookbook#570]
The default deb / rpm download location for the rabbitmq server packages is pointing to dl.bintray.com. Today, Bintray temporarily disabled downloads from these URLs as part of their deprecation timeline. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ 

Should these default URLs be updated to a service that will be continuing to operate past May 1?

**Comment by michaelklishin** [comment]
You are welcome to do it and submit a PR. The [list of options](https://blog.rabbitmq.com/posts/2021/03/migrate-off-of-bintray/) has been announced a couple of weeks ago.

Cloudsmith makes most sense for packages. GitHub should be used for generic binary builds (which this cookbook probably doesn't use, I don't really remember).

**Comment by michaelklishin** [comment]
This was done for `5.9.0`.
