### ISSUE TITLE
Code error: providers/cluster.rb#L259

### ISSUE THREAD

**Issue by kevinleiyan** [rabbitmq/chef-cookbook#576]
hi

I am chef/ruby newbie, When I read your code on https://github.com/rabbitmq/chef-cookbook/blob/v5.x/providers/cluster.rb#L259，I found you use 'node['name'] == var_node_name' not 'node['name'] = var_node_name'.  I thought it is wrong. if not, please ignore and close the issue.

**Comment by michaelklishin** [comment]
The expression is used in an `Array#select` predicate, so it is meant to be a comparison. The idea is to find the entry for the current node and then look up its intended type (`disk` or `ram`).
