### ISSUE TITLE
Unable to install versions 24 or 25 of erlang on Ubuntu 18.04

### ISSUE THREAD

**Issue by nikolawannabe** [rabbitmq/chef-cookbook#615]
### Describe the bug

Might be worth a note in the README that Cloudsmith no longer carries binaries for Ubuntu 18.04 for versions 24+ of erlang.  (I just bumped my version down to 23 for now which is still available.)

The error message was very unhelpful that this was the root cause, and it took me a while to track it down.

### Reproduction steps

1. Attempt to run coookbook on Ubuntu 18.04 with versions 24 or 25 configured
...

### Expected behavior

Probably just a readme note in the compatibility section is fine.

### Additional context

For now, I ended up just downloading all the erlang packages for this version (1:23.3.4.19-1) for bionic manually from Cloudsmith and uploading them to our s3, then installing them with dpkg manually and disabling the erlang cookbook.  (There's no telling when they'll pull all the 23 binaries too.)

**Comment by michaelklishin** [comment]
This is not an Erlang cookbook.

Ubuntu 18.04 has reached end of life [close to a year ago](https://ubuntu.com/blog/18-04-end-of-standard-support). You [cannot even quickly find out](https://packages.ubuntu.com/search?keywords=openssl-dev&searchon=names&suite=all&section=all) what OpenSSL version it ships with, which is critically important for modern Erlang versions.

It's not on OSS maintainers to list Ubuntu 18.04 compatibility explicitly. It's an objectively old version very few maintainers would care about. It's on you to upgrade or use older versions of various tools.

**Comment by michaelklishin** [comment]
As of https://github.com/rabbitmq/chef-cookbook/commit/a342c5cf6e7f41babca68afae3aab98e00145eed the README no longer promises Ubuntu 18.04 support. Sorry about that, this project has fallen well behind RabbitMQ's own evolution. There's only so much a small core team can do.
